Stack overflow questions scraper
avinashkranjan/Amazing-Python-Scripts pull request #1011
Opened 2021-05-04 17:05 UTC by Ayushjain2205

# Description

Script to scrape questions from stack overflow based on users choice of question tag (python, java etc)

## Fixes #995 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-05-06 12:27 UTC, kaustubhgupta requested changes
Add an option to control how many questions to be scrapped.

2021-05-07 21:27 UTC, Ayushjain2205 commented
Sure will make the changes

2021-05-11 05:57 UTC, kaustubhgupta requested changes
Update the PR template with project meta data

2021-05-11 11:38 UTC, Ayushjain2205 commented
@kaustubhgupta  Changes made to PR template

2021-05-11 12:41 UTC, kaustubhgupta approved these changes
💯

2021-05-11 13:25 UTC, antrikshmisri approved these changes

2021-05-12 05:42 UTC, santushtisharma10 approved these changes

2021-05-27 05:51 UTC, avinashkranjan approved these changes

2021-05-27 05:51 UTC, merged