Email GUI
avinashkranjan/Amazing-Python-Scripts pull request #1032
Opened 2021-05-11 06:34 UTC by Amit366

# Description

Added Email sender gui script

## Fixes #992 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Email sender GUI

Folder: Email GUI

Requirements: tkinter, smtplib

Script: script.py

Arguments: none

Contributor: Amit Kumar Mishra

Description: An email sender Gui to send emails

2021-05-12 05:05 UTC, kaustubhgupta requested changes

2021-05-12 05:05 UTC, kaustubhgupta commented on Email GUI/script.py
> +    #sender_password = input("Enter password: ")
you can remove these comments

2021-05-12 05:05 UTC, kaustubhgupta commented on Email GUI/script.py
> +    sender_address_entry(0,END)
This is not defined between the line 1 to 35 and that's why the pylint is showing error

2021-05-14 04:26 UTC, kaustubhgupta requested changes
you have force pushed the branch and that's why other commits are present in this PR. Kindly fix it. For future ref, don't force push branch until extremely imp

2021-05-14 04:34 UTC, Amit366 commented
@kaustubhgupta I have removed the extra files

2021-05-15 05:32 UTC, kaustubhgupta requested changes
Just a readme update :)

2021-05-15 05:32 UTC, kaustubhgupta commented on Email GUI/Readme.md
> +    - tkinter
```suggestion
- smtplib
- tkinter
```

2021-05-15 05:32 UTC, kaustubhgupta commented on Email GUI/Readme.md
> +   Amit Kumar Mishra
```suggestion
[Amit Kumar Mishra](https://github.com/Amit366)
```

2021-05-15 08:34 UTC, kaustubhgupta approved these changes

2021-05-17 02:16 UTC, Kushal997-das approved these changes
LGTM 👍

2021-05-17 04:14 UTC, santushtisharma10 approved these changes

2021-05-21 07:35 UTC, antrikshmisri approved these changes

2021-05-27 05:52 UTC, merged