Added 'Laptop Price Predictor' Project
avinashkranjan/Amazing-Python-Scripts pull request #1043
Opened 2021-05-11 15:45 UTC by Manasi2001

# Description

The folder structure goes like this:

Laptop Price Predictor

▫Dataset
- laptoppricing.csv

▫GUI
- app.py

▫Model
- Laptop_Price_Prediction.py
- LaptopPricePrediction.pkl

▫README

## Fixes #1029 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [x] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Laptop Price Predictor

Folder: Model

Requirements: None

Script: Laptop_Price_Prediction.py

Arguments: None

Contributor: Manasi2001

Description: This 'Laptop Price Predictor' provided with a UI, can very accurately predict the prices of laptops on the basis of companies, model features, etc.

![image](https://user-images.githubusercontent.com/68627617/117845180-efef9e80-b29d-11eb-8a92-3b2e6ef8b040.png)

2021-05-12 05:31 UTC, santushtisharma10 requested changes

2021-05-12 05:31 UTC, santushtisharma10 commented on Laptop Price Predictor/GUI/app.py
> +
```suggestion
model = joblib.load(r'./Laptop Price Predictor/Model/LaptopPricePrediction.pkl')

```

2021-05-12 05:31 UTC, santushtisharma10 commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +
```suggestion

df = pd.read_csv(r'./Laptop Price Predictor/Dataset/laptoppricing.csv', encoding = 'unicode_escape')

```

2021-05-12 05:31 UTC, santushtisharma10 commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +pickle.dump(regr, open('LaptopPricePrediction.pkl', 'wb'))
```suggestion
# Getting the pkl file

import pickle
pickle.dump(regr, open('./Laptop Price Predictor/Model/LaptopPricePrediction.pkl', 'wb'))
```

2021-05-12 05:36 UTC, santushtisharma10 commented
Also include the case if user enters any other brand than ASUS, DELL, HP, Lenovo .

2021-05-14 07:11 UTC, santushtisharma10 commented
@Manasi2001 instead of closing the application you should display a statement in the result like price can't be predicted due to lack of data of given model/manufacturer.

2021-05-14 07:33 UTC, antrikshmisri approved these changes

2021-05-14 12:52 UTC, Manasi2001 commented
@santushtisharma10 please check now.

2021-05-15 05:48 UTC, kaustubhgupta requested changes

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/README.md
> +Manasi Chhibber
```suggestion
[Manasi Chhibber](https://github.com/Manasi2001)
```

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +print('\n',df.columns)
you can remove this

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +df['ï»¿Manufacturer'] = df['ï»¿Manufacturer'].astype('|S')
what is this character?: `ï»¿`Manufacturer 

if the column is not clean, then add the step to clean it

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +print('\n',vif)
```suggestion
print('Variance inflation factor is: ',vif)
```

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +print('\nAccuracy:',r2_score(y_test, y_pred))
```suggestion
print('\nAccuracy (r2_score) :  ',r2_score(y_test, y_pred))
```

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +# Predictions are 98.79% accurate.
remove this

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/GUI/app.py
> +import joblib
shift this file to `Laptop Price Predictor` folder

2021-05-15 05:48 UTC, kaustubhgupta commented on Laptop Price Predictor/GUI/app.py
> +        m = 3
can we have a dropdown for the manufacturer? It will eliminate the user error for the wrong manufacturer

2021-05-15 05:49 UTC, kaustubhgupta reviewed
add the requirements.txt file

2021-05-16 03:56 UTC, santushtisharma10 approved these changes

2021-05-16 05:11 UTC, kaustubhgupta requested changes
Drop down menu for manufacturer is still missing. Also:

2021-05-16 05:11 UTC, kaustubhgupta commented on Laptop Price Predictor/app.py
> +model = joblib.load('..\Laptop Price Predictor\Model\LaptopPricePrediction.pkl')
```suggestion
model = joblib.load('.\Laptop Price Predictor\Model\LaptopPricePrediction.pkl')
```

2021-05-16 05:11 UTC, kaustubhgupta commented on Laptop Price Predictor/Model/Laptop_Price_Prediction.py
> +df.rename(columns={'ï»¿Manufacturer':'Manufacturer'}, inplace=True)
on writing this simple code, I am not getting any special characters for manufacturer:

```python
import pandas as pd

df = pd.read_csv(r"Laptop Price Predictor\Dataset\laptoppricing.csv")
print(df.columns)
```
Output:
```bash
Index(['Manufacturer', 'IntelCore(i-)', 'IntelCoreGen',
       'processing speed(GHz)', 'Ram(gb)', 'HDD(gb)', 'SSD(gb)',
       'Graphics(gb)', 'ScreenSize(inch)', 'Price'],
      dtype='object')
```
Just read the dataset without any encoding

2021-05-16 05:15 UTC, kaustubhgupta requested changes

2021-05-16 05:15 UTC, kaustubhgupta commented on Laptop Price Predictor/app.py
> +    label_Prediction = tk.Label(root, text= Prediction_result, bg='orange')
This is not coming out attractive:

![image](https://user-images.githubusercontent.com/43691873/118386232-a7d0d300-b633-11eb-8358-9fe1b44f0f92.png)

Curly braces with square brackets, just display the price value with appropriate currency symbol

2021-05-19 08:17 UTC, kaustubhgupta commented
@Manasi2001 Updates on this?

2021-05-19 14:31 UTC, Manasi2001 commented
> @Manasi2001 Updates on this?

I'm not willing to work on this anymore @kaustubhgupta.

2021-05-19 15:02 UTC, closed without merging