Twitter Video Downloader
avinashkranjan/Amazing-Python-Scripts pull request #1046
Opened 2021-05-13 05:50 UTC by XZANATOL

# Description

Added Twitter video downloader project files. I figured a workaround for adding a detailed progress bar for the download. It's a bit of a personal preference to see detailed info of the download progress.

## Fixes #1039

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [x] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Twitter Video Downloader

Folder: Twitter_Video_Downloader

Requirements: Twitter_Video_Downloader\requirements.txt

Script: script.py

Arguments: none

Contributor: XZANATOL

Description: GUI App that downloads twitter video from its provided URL

2021-05-15 05:59 UTC, kaustubhgupta requested changes
Initially there is a black screen with no text. this doesn't give a good look. Can you add some text for that, like: welcome to twitter downloader and then it disappears when the download process starts?

2021-05-15 05:59 UTC, kaustubhgupta commented on Twitter_Video_Downloader/Readme.md
> +# Twitter Video Downloader
can we decrease all the heading levels after this one to level 2 (##). This is look good I guess

2021-05-15 05:59 UTC, kaustubhgupta commented on Twitter_Video_Downloader/Readme.md
> +A GUI used to download
A GUI used to download ... ? next?

2021-05-15 06:31 UTC, XZANATOL commented
You need to start the download for the progress to show up. xd

But I got your point, gonna make tge changes.

2021-05-15 12:35 UTC, kaustubhgupta approved these changes

2021-05-15 18:34 UTC, Kushal997-das approved these changes
LGTM 👍

2021-05-16 03:45 UTC, santushtisharma10 approved these changes

2021-05-21 07:34 UTC, antrikshmisri approved these changes
Sorry for the delay. LGTM 👍🏻

2021-05-27 06:06 UTC, avinashkranjan approved these changes

2021-05-27 06:06 UTC, merged