Akm
avinashkranjan/Amazing-Python-Scripts pull request #1057
Opened 2021-05-15 11:39 UTC by Amit366

# Description

Added script to download facebook video
## Fixes #1037 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Fcaebook video downloader

Folder: Facebook_Video_Downloader
Requirements: urllib.requests

Script: script.py
Arguments: none

Contributor: Amit Kumar Mishra

Description: Added script to download facebook video

2021-05-15 11:40 UTC, Amit366 commented
@kaustubhgupta  can u please help me with progress bar?

2021-05-16 05:23 UTC, kaustubhgupta requested changes

2021-05-16 05:23 UTC, kaustubhgupta commented on Facebook_Video_downloader/script.py
> +print("downloading......")
This is not working, I tried with this link: https://www.facebook.com/herowarsgame/videos/961066781305631/

A file was downloaded but it's not playing. Also, as mentioned in the issue description, implement the GUI and then we will see if progress bar can be implemented

2021-05-16 05:29 UTC, Amit366 commented
Ok

2021-05-19 08:17 UTC, kaustubhgupta commented
@Amit366 updates on this?

2021-05-19 08:25 UTC, Amit366 commented
@kaustubhgupta i am unwell. So I request you to please give me 3 more days.

2021-05-19 08:27 UTC, kaustubhgupta commented
> @kaustubhgupta i am unwell. So I request you to please give me 3 more days.

okay, take rest!

2021-05-21 10:22 UTC, Amit366 commented
@kaustubhgupta I tried implementing the progress bar but it is showing an error .

2021-05-22 02:50 UTC, kaustubhgupta requested changes
Not working (link tried:  https://www.facebook.com/cistheta/videos/983590405510302)

![image](https://user-images.githubusercontent.com/43691873/119212431-d76d5880-bad5-11eb-80bd-823152d52734.png)

Also, you are again doing plagiarism: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1046/files. You have copied the code from this PR as it is without even changing fonts, comments, displayed a big blue screen, the purpose of that is still unpredictable. 

I can easily put 3rd strike on this which would nullify all your scores in entire GSSOC. But I am giving you last chance to improve. Come up with GUI of your own, fix the video downloading issues.

2021-05-22 03:07 UTC, Amit366 commented
@kaustubhgupta I can do it with progress bar without GUI

2021-05-22 03:08 UTC, Amit366 commented
If you want I can do else I cannot do GUI

2021-05-22 03:15 UTC, kaustubhgupta commented
Implement it with GUI and without progress bar

2021-05-22 03:18 UTC, Amit366 commented
@kaustubhgupta I am facing problem with GUI that's why I am asking you that can I implement without GUI

2021-05-22 03:27 UTC, kaustubhgupta commented
> @kaustubhgupta I am facing problem with GUI that's why I am asking you that can I implement without GUI

this issue is supposed to be solved in GUI only. If you're facing issues then feel free to drop it. Also, as you are facing issues with this, I think you won't be able to solve the LinkedIn video downloader GUI too.

2021-05-23 11:54 UTC, closed without merging