Real Estate Property Data #1003
avinashkranjan/Amazing-Python-Scripts pull request #1060
Opened 2021-05-16 00:10 UTC by Himanshi2997

# Description

To make a program to extract required information from web pages and put the data in well structured format using beautiful soup library in python.

## Fixes #1003

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata
none

Category:
- [ ] Scrappers

Title: \real_estate_webscrapper.py

Folder: \Real Estate Webscrapper

Requirements: \README.md

Script: \real_estate_webscrapper.py

Contributor: \Himanshi2997

Description: \Take data from real estate websites and chart them in tabular form.

2021-05-16 05:29 UTC, kaustubhgupta requested changes

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/README.md
> +### Requirements
```suggestion
## Requirements
```

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/README.md
> +### How To install
```suggestion
## How To install
```

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/README.md
> +### Author
```suggestion
## Author
```

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/README.md
> +- Himanshi2997
```suggestion
[Himanshi2997](https://github.com/Himanshi2997)
```

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/README.md
> +### Output
```suggestion
## Output
```

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/output2.csv
> +10,1Cr,,2 BHK,"Geetanjali Enclave, Malviya Nagar ",500 sqft
delete this output file

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/real_estate_webscrapper.py
> +    d={}
can we use a better variable name that can explain the code better?

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/real_estate_webscrapper.py
> +    s=""
can we use a better variable name that can explain the code better?

2021-05-16 05:29 UTC, kaustubhgupta commented on Real Estate Webscrapper/real_estate_webscrapper.py
> +df.to_csv("output2.csv")
```suggestion
df.to_csv("./Real Estate Webscrapper/scraped.csv")
```

2021-05-17 04:00 UTC, kaustubhgupta approved these changes

2021-05-17 04:03 UTC, kaustubhgupta requested changes
- add the requirements.txt file
- Update the PR template properly, adhere to the template provided. Check out approved PRs for better understanding

2021-05-18 06:08 UTC, kaustubhgupta requested changes

2021-05-18 06:08 UTC, kaustubhgupta commented on Real Estate Webscrapper/requirements.txt
> +5. python==3.9.4
this is not the way of defining the requirements file. Check out this file for ref: https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Amazon-Price-Alert/requirements.txt

2021-05-19 08:19 UTC, kaustubhgupta commented on Real Estate Webscrapper/requirements.txt
> +python==3.9.4
not valid requirements, remove them

2021-05-19 14:22 UTC, kaustubhgupta approved these changes

2021-05-20 03:33 UTC, santushtisharma10 approved these changes
LGTM

2021-05-20 15:52 UTC, antrikshmisri approved these changes
LGTM

2021-05-27 06:06 UTC, avinashkranjan approved these changes

2021-05-27 06:06 UTC, merged