Medium scraper
avinashkranjan/Amazing-Python-Scripts pull request #1075
Opened 2021-05-18 17:35 UTC by Ayushjain2205

# Description

Script to scrape articles from medium depending on user input

## Fixes #1040 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Medium Scraper

Folder: Medium-Scraper

Requirements: requirements.txt

Script: scraper.py

Arguments: none

Contributor: Ayushjain2205

Description: Script to scrape articles from medium.com

2021-05-19 08:44 UTC, kaustubhgupta requested changes

2021-05-19 08:44 UTC, kaustubhgupta commented on Medium-Scraper/README.md
> +# Dev.to Scrapper
Umm, Maybe it's Medium? 😆

2021-05-19 08:56 UTC, Ayushjain2205 commented on Medium-Scraper/README.md
> +# Dev.to Scrapper
Oops my bad! resolved it now!

2021-05-19 09:28 UTC, kaustubhgupta approved these changes

2021-05-19 10:02 UTC, santushtisharma10 approved these changes
@Ayushjain2205 💯

2021-05-19 10:35 UTC, Kushal997-das approved these changes
LGTM 👍

2021-05-27 06:05 UTC, avinashkranjan approved these changes
LGTM

2021-05-27 06:05 UTC, merged