Address-book
avinashkranjan/Amazing-Python-Scripts pull request #1081
Opened 2021-05-20 17:22 UTC by sameeksharl

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #829

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [x] Others

Title: Address-book

Folder: Address-book

Requirements: None

Script: addressbook.py

Arguments: none

Contributor: sameeksharl

Description: This project is to create an Address book in which the user can add a new contact, edit and delete existing contact and view all the contacts.

2021-05-20 17:24 UTC, sameeksharl commented
@kaustubhgupta Could you please review the pr?

2021-05-21 06:18 UTC, kaustubhgupta requested changes
- Flash a message when a contact is added or deleted (not in terminal)
- When contact is deleted, it still shows in the view all list. 
- Other changes:

2021-05-21 06:18 UTC, kaustubhgupta commented on Address-Book/Readme.md
> +
remove these blank lines

2021-05-21 06:18 UTC, kaustubhgupta commented on Address-Book/Readme.md
> +# Setup instructions
All subheadings after Address-Book heading should be level 2 (##)

2021-05-21 06:18 UTC, kaustubhgupta commented on Address-Book/Readme.md
> +	pip install tkinter
tkinter comes preinstalled with python, you can remove this section

2021-05-21 06:18 UTC, kaustubhgupta commented on Address-Book/Readme.md
> +* In this python project, the user has to click on a button which functions the user wants to access
Can you rewrite it? 
```suggestion
* In this python project, the user has button functionality to trigger that specific function.
```

2021-05-21 06:18 UTC, kaustubhgupta commented on Address-Book/addressbook.py
> +database = r"addressbook.db"
```suggestion
database = r"./Address-Book/addressbook.db"
```

2021-05-21 08:17 UTC, sameeksharl commented
@kaustubhgupta its deleted only if we click on 'view all' again after deleting right??
I didn't get this issue ? could u pls tell me again so that i can rectify ??

2021-05-21 10:02 UTC, sameeksharl commented
Could u pls check now??? @kaustubhgupta

2021-05-22 03:14 UTC, kaustubhgupta approved these changes

2021-05-22 03:55 UTC, sameeksharl commented
Thank you for your response!!

On Sat, 22 May 2021, 8:44 am Kaustubh Gupta, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1081#pullrequestreview-666146985>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOIEAAISIZFQWV75DJFONBTTO4OR3ANCNFSM45HPL4UQ>
> .
>

2021-05-23 15:17 UTC, santushtisharma10 approved these changes
LGTM

2021-05-26 07:51 UTC, sameeksharl commented
@kaustubhgupta  @avinashkranjan could u pls merge the pr??
as @avinashkranjan also said LGTM

2021-05-26 09:24 UTC, kaustubhgupta commented
> @kaustubhgupta @avinashkranjan could u pls merge the pr??
> as @avinashkranjan also said LGTM

PA (avinash) is yet to review the PR. He will merge the PR soon or on the last date of GSSOC. Kindly have patience. You will get your points for PR.

2021-05-26 13:09 UTC, sameeksharl commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->Thanks for the info !!! not about points, just a verification .Wanted make sure it is reviewed coz some other project’s mentors are not verifying either its been a month . Sent from Mail for Windows 10 From: Kaustubh GuptaSent: 26 May 2021 14:55To: avinashkranjan/Amazing-Python-ScriptsCc: sameeksharl; AuthorSubject: Re: [avinashkranjan/Amazing-Python-Scripts] Address-book ***@***.*** @avinashkranjan could u pls merge the pr??as @avinashkranjan also said LGTMPA (avinash) is yet to review the PR. He will merge the PR soon or on the last date of GSSOC. Kindly have patience. You will get your points for PR.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-05-27 06:04 UTC, avinashkranjan approved these changes
LGTM..

2021-05-27 06:05 UTC, merged