Code
avinashkranjan/Amazing-Python-Scripts pull request #1082
Opened 2021-05-20 19:35 UTC by Muskan0

# Description

I added the Stack Overflow Tool. It will execute a python script, if there will be any errors, some of the related Stack Overflow questions will be opened in the browser.

## Fixes #1063 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Stack Overflow Error Search Auto Tool

Folder: Stackoverflow-Tool

Requirements: requirements.txt

Script: script.py

Arguments: None

Contributor: Muskan0

Description: This script executes your python file and it opens up the related Stack Overflow threads in the browser if there's any error in the script.

2021-05-21 06:14 UTC, kaustubhgupta requested changes

2021-05-21 06:14 UTC, kaustubhgupta commented on Stackoverflow-Tool/filename.py
> +# this is the python script taken as an example
you can remove this file

2021-05-21 06:14 UTC, kaustubhgupta commented on Stackoverflow-Tool/script.py
> +p = subprocess.run(['python', 'filename.py'], capture_output=True, text=True)
get the file name or exact path from the user

2021-05-21 06:14 UTC, kaustubhgupta commented on Stackoverflow-Tool/README.md
> +- Install these python libraries: subprocess, requests and webbrowser.
you can remove this section

2021-05-21 13:00 UTC, Muskan0 commented
@kaustubhgupta I did the changes, please review it.

2021-05-22 03:21 UTC, kaustubhgupta approved these changes
good

2021-05-24 11:13 UTC, santushtisharma10 approved these changes

2021-05-27 06:04 UTC, avinashkranjan approved these changes
LGTM..💯

2021-05-27 06:04 UTC, merged