Added Project files
avinashkranjan/Amazing-Python-Scripts pull request #1083
Opened 2021-05-21 04:58 UTC by XZANATOL

# Description

Added vector calculator files.

## Fixes #1045 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [x] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Vector Calculator

Folder: Vector_Calc

Requirements: Vector_Calc\requirements.txt

Script: script.py

Arguments: none

Contributor: XZANATOL

Description: A GUI based script that allows user to fetch relations between 2 vectors along with the properties of each vector.

2021-05-21 06:24 UTC, kaustubhgupta requested changes
This case was not handled:
![image](https://user-images.githubusercontent.com/43691873/119091857-4d68b580-ba2b-11eb-87fa-bb5a298e9668.png)

2021-05-22 02:34 UTC, kaustubhgupta approved these changes

2021-05-24 16:02 UTC, santushtisharma10 approved these changes

2021-05-27 06:03 UTC, avinashkranjan approved these changes
LGTM..💯

2021-05-27 06:03 UTC, merged