DNS
avinashkranjan/Amazing-Python-Scripts pull request #1084
Opened 2021-05-21 04:59 UTC by sur16-cse

# Description

A Script to verify the Domain Name System.
- This is useful to check for the availability of DNS.

## Fixes #(1079)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
-[x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: DNS verifier

Folder: DNS verifier

Requirements:  requirements.txt

Script: main.py

Arguments: --dns <DNS>

Contributor: sur16-cse

Description: Script to verify the Domain Name System. The argument is needed as to check users DNS request check.

2021-05-21 06:26 UTC, kaustubhgupta requested changes
minor change:

2021-05-21 06:26 UTC, kaustubhgupta commented on DNS verifier/readme.MD
> +### Language
```suggestion
## Language
```

2021-05-21 06:26 UTC, kaustubhgupta commented on DNS verifier/readme.MD
> +### Instructions to run this application
```suggestion
## Instructions to run this application
```

2021-05-21 07:39 UTC, sur16-cse commented
@avinashkranjan  made the changes in readme please review it.

2021-05-22 03:33 UTC, kaustubhgupta reviewed
we generally face issues while integrating argument based scripts into the master script. Can you refactor your code that accepts DNS name from user and then you display the verification information?

2021-05-22 04:19 UTC, sur16-cse commented
Yup sure i will update it

On Sat, 22 May 2021, 09:04 Kaustubh Gupta, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> we generally face issues while integrating argument based scripts into the
> master script. Can you refactor your code that accepts DNS name from user
> and then you display the verification information?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1084#pullrequestreview-666148165>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQF6RGT2IMJQHKFTATJUYOLTO4Q27ANCNFSM45IM256A>
> .
>

2021-05-22 04:50 UTC, sur16-cse commented
@avinashkranjan restructured the code in main.py and made changes in the readme.MD accordingly. Please review it.

2021-05-22 05:10 UTC, kaustubhgupta approved these changes

2021-05-22 10:05 UTC, sur16-cse commented
Thanks

On Sat, 22 May 2021, 10:40 Kaustubh Gupta, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1084#pullrequestreview-666153055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQF6RGU26XTLFYG636JQXMDTO44FVANCNFSM45IM256A>
> .
>

2021-05-24 16:29 UTC, santushtisharma10 approved these changes

2021-05-27 06:01 UTC, avinashkranjan approved these changes
LGTM..

2021-05-27 06:02 UTC, merged