Pomodoro GUI
avinashkranjan/Amazing-Python-Scripts pull request #1087
Opened 2021-05-21 10:23 UTC by RohiniRG

# Description

The Pomodoro technique uses a timer to break down work into intervals, traditionally 25 minutes in length, separated by 5 min breaks. The python script is represented in a GUI based form along with an extra functionality of website blocking to prevent distractions.

## Fixes #1044 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update
- [X] Documentation Update

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [X] I have added the project meta data in the PR template.
- [X] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [X] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [X] Fun
- [ ] Others

Title: Pomodoro clock with GUI

Folder: Pomodoro_GUI

Requirements: requirements.txt

Script: Pomodoro_gui.py.

Arguments: None

Contributor: RohiniRG

Description:The Pomodoro technique uses a timer to break down work into intervals, traditionally 25 minutes in length, separated by 5 min breaks. The python script is represented in a GUI based form along with an extra functionality of website blocking to prevent distractions.

2021-05-22 04:14 UTC, kaustubhgupta requested changes
Some enhancements:

2021-05-22 04:14 UTC, kaustubhgupta commented on Pomodoro_GUI/Pomodoro_gui.py
> +]
can we get this input via GUI? it will make the script more customizable.

2021-05-22 04:14 UTC, kaustubhgupta commented on Pomodoro_GUI/Pomodoro_gui.py
> +    pygame.mixer.music.load("beep.wav")
```suggestion
    pygame.mixer.music.load("./Pomodoro_GUI/beep.wav")
```

2021-05-22 04:14 UTC, kaustubhgupta commented on Pomodoro_GUI/Pomodoro_gui.py
> +    bg = tk.PhotoImage(file = "bg.png")
```suggestion
    bg = tk.PhotoImage(file = "./Pomodoro_GUI/bg.png")
```

2021-05-22 05:58 UTC, RohiniRG commented
> Some enhancements:

Yes, I will try to implement this.
But @kaustubhgupta could you please consider upgrading the level for this issue, as I believe I had to put a lot more work into this than other level2 issues I have submitted for this repo.

2021-05-22 06:04 UTC, kaustubhgupta commented
> > Some enhancements:
> 
> Yes, I will try to implement this.
> But @kaustubhgupta could you please consider upgrading the level for this issue, as I believe I had to put a lot more work into this than other level2 issues I have submitted for this repo.

will consider that after the script is ready to be approved 👍

2021-05-23 13:57 UTC, RohiniRG commented
@kaustubhgupta have a look

2021-05-24 13:48 UTC, kaustubhgupta approved these changes
Perfect, increased the level as promised :)

2021-05-25 06:33 UTC, santushtisharma10 approved these changes

2021-05-27 05:58 UTC, avinashkranjan approved these changes
LGTM..

2021-05-27 05:59 UTC, merged