Added File Downloader
avinashkranjan/Amazing-Python-Scripts pull request #1094
Opened 2021-05-22 14:12 UTC by noviicee

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1056 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: \File Downloader

Folder: \File Downloader

Requirements: \None

Script: \file_downloader.py

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: \noviicee

Description: \This python script will help users to download any kind of files, irrespective of their size from the internet.
You just need to have the url and you are good to go!

2021-05-23 12:01 UTC, kaustubhgupta requested changes

2021-05-23 12:01 UTC, kaustubhgupta commented on File Downloader/file_downloader.py
> +with open("file.pdf","wb") as file:
will everyone download pdf? you just mentioned in the readme:
```
This python script will help users to download any kind of files, irrespective of their size from the internet.
```
fix this

2021-05-23 12:02 UTC, kaustubhgupta reviewed
PR template also wrongly filled

2021-05-24 13:53 UTC, kaustubhgupta approved these changes

2021-05-27 03:19 UTC, santushtisharma10 approved these changes

2021-05-27 05:56 UTC, merged