Mini audacity
avinashkranjan/Amazing-Python-Scripts pull request #1106
Opened 2021-05-24 06:15 UTC by A-kriti

# Description

Added a new folder "Mini Audacity" containing all the required files.

## Fixes #(1102)

## Type of change

- [✓] New feature (non-breaking change which adds functionality)

## Checklist:
- [✓] My code follows the style guidelines(Clean Code) of this project
- [✓] I have performed a self-review of my own code
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] I have created a helpful and easy to understand README.md

## Project Metadata

Category:

- [✓] AI/ML
- [✓] Others

Title: \<Mini Audacity\>

Folder: \<Mini Audacity\>

Requirements: \<Required to install python packages ->scipy, NumPy, librosa, scipy.io.wavfile, Matplotlib, scipy.io\>

Script: \<Mini Audacity.ipynb\>

Contributor: \<A-kriti\>

Description: \<Removing background noise from an audio file just like "Audacity"\>

2021-05-24 08:06 UTC, santushtisharma10 commented
@A-kriti the script should be a python file. Also include requirements.txt file in the folder

2021-05-24 08:11 UTC, santushtisharma10 commented
And both the PR template is not correctly filled. Refer to approved PR and make changes accordingly

2021-05-24 09:36 UTC, A-kriti commented
Done @santushtisharma10 ma'am!

2021-05-24 10:47 UTC, santushtisharma10 commented
requirements.txt is empty file. Refer to this [page](https://stackoverflow.com/questions/31684375/automatically-create-requirements-txt) to make a one.

2021-05-24 15:43 UTC, A-kriti commented
@santushtisharma10 ma'am, it's empty in both the cases

![Screenshot (407)](https://user-images.githubusercontent.com/73133055/119372307-c50d3d80-bcd4-11eb-8685-51a8e8e04b4d.png)

2021-05-24 16:27 UTC, santushtisharma10 commented
@A-kriti try using the command piqreqs [folder location] or you can manually write in the file.
![image](https://user-images.githubusercontent.com/60578091/119377702-0acd0480-bcdb-11eb-83ad-376a266dda0c.png)

the above commands worked for me
![image](https://user-images.githubusercontent.com/60578091/119377524-db1dfc80-bcda-11eb-9fbf-0b44e46a7877.png)

2021-05-24 16:46 UTC, A-kriti commented
> @A-kriti try using the command piqreqs [folder location] or you can manually write in the file.
> ![image](https://user-images.githubusercontent.com/60578091/119377702-0acd0480-bcdb-11eb-83ad-376a266dda0c.png)
> 
> the above commands worked for me
> ![image](https://user-images.githubusercontent.com/60578091/119377524-db1dfc80-bcda-11eb-9fbf-0b44e46a7877.png)

@santushtisharma10 ma'am, thanks for this!

2021-05-27 03:58 UTC, santushtisharma10 commented
@A-kriti your code is almost same as this [code](https://github.com/shun60s/spectral-subtraction/blob/master/ss1.py). You just have added the code to display those graphs, rest the logic is exactly same as the this [code](https://github.com/shun60s/spectral-subtraction/blob/master/ss1.py)

2021-05-27 17:33 UTC, A-kriti commented
@santushtisharma10 ma'am,  I had changed everything. Now, pls have a look!!

2021-05-28 13:12 UTC, kaustubhgupta requested changes
- Change the folder and script name to 'Noise Reduction Script' as audacity has a lot of features and this script is only for noise reduction. Also, make the changes to the README file accordingly.

Other changes:

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/Mini Audacity.py
> +file = input("Enter the path here :")
```suggestion
file = input("Enter the file path: ")
```

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/Mini Audacity.py
> +ax.set_title('Spectral Subtraction Method', fontsize=15)
You have not displayed the graph to the user. Save the graph generated by the script in the same method as done in previous PR (audio file name (Spectral Subtraction graph).jpg) in the same folder `Mini Audacity`

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/Mini Audacity.py
> +wav.write(cleaned_file,rate=sr, data = clean_data.astype(np.int16))
save the file in same folder `Mini Audacity` with name `Filtered Audio (original file name)`

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/Mini Audacity.py
> +
remove 2 extra lines from the end

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/README.md
> +
remove these blank lines

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/README.md
> +Akriti
```suggestion
[Akriti](https://github.com/A-kriti)
```

2021-05-28 13:12 UTC, kaustubhgupta commented on Mini Audacity/README.md
> +
remove these blank lines

2021-05-28 13:22 UTC, kaustubhgupta reviewed
Also, update the PR template properly

2021-05-31 01:56 UTC, kaustubhgupta approved these changes
a bug is still there but anyways, due to less time, we will merge it.

2021-05-31 04:44 UTC, santushtisharma10 approved these changes

2021-05-31 06:29 UTC, antrikshmisri approved these changes

2021-06-05 06:37 UTC, merged