#1103 JobScraper Added
avinashkranjan/Amazing-Python-Scripts pull request #1110
Opened 2021-05-24 18:14 UTC by iamakkkhil

# Description

- The python script uses BeautifulSoup to scrape job opening postings on indeed.com.
- The script takes user input for the required job title, location, the number of posts to collect and collect all the associated information.
- The information collected is stored in a `.csv` file.

## Fixes #1103 

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
 
## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Job Scraper from Indeed

Folder: Job Scraper

Requirements: requirements.txt

Script: JobScraper.py

Arguments: None

Contributor: @iamakkkhil 

Description: The python script uses BeautifulSoup to scrape job opening postings on indeed.com.

2021-05-25 06:51 UTC, santushtisharma10 approved these changes
LGTM

2021-05-26 04:57 UTC, Kushal997-das approved these changes
LGTM :)

2021-05-26 10:13 UTC, kaustubhgupta requested changes

2021-05-26 10:13 UTC, kaustubhgupta commented on Job Scraper/JobScraper.py
> +    with open(loc+'_openings.csv', 'a', encoding='utf-8') as csv_f:
```suggestion
    with open('./Job Scraper/' + loc+'_openings.csv', 'a', encoding='utf-8') as csv_f:
```

2021-05-26 10:51 UTC, kaustubhgupta approved these changes

2021-05-27 05:48 UTC, avinashkranjan approved these changes
LGTM..💯

2021-05-27 05:48 UTC, merged