Neon Effect Filter #1117
avinashkranjan/Amazing-Python-Scripts pull request #1125
Opened 2021-05-26 16:32 UTC by A-kriti

# Description

Added new folder "Neon Effect Filter" containing all the required files!

## Fixes #(1117)

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows Template for README.md
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Project Metadata

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [x] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: \<Neon Effect Filter\>

Folder: \<Neon Effect Filter\>

Requirements: \<requirements.txt\>

Script: \<Code.py\>

Arguments: \<none\>

Contributor: \<A-kriti\>

Description: \<Implementing a "Neon Effect Filter" using OpenCV, Matplotlib, Os, and NumPy.\>

2021-05-28 14:05 UTC, kaustubhgupta requested changes
- PR template wrongly updated
- Other changes:

2021-05-28 14:05 UTC, kaustubhgupta commented on Neon Effect Filter/Code.py
> +plt.savefig("(Neon Effect Filter)"+filename)  #saved file name as (Filtered)image_name.jpg
```suggestion
plt.savefig("./Neon Effect Filter/Neon Effect Filter"+filename)  #saved file name as (Filtered)image_name.jpg
```

2021-05-31 02:01 UTC, kaustubhgupta approved these changes
cool 👍🏼 💯

2021-05-31 05:54 UTC, santushtisharma10 approved these changes

2021-06-05 16:18 UTC, avinashkranjan approved these changes
LGTM..🚩

2021-06-05 16:19 UTC, merged