Added Certificate-Sender
avinashkranjan/Amazing-Python-Scripts pull request #1131
Opened 2021-05-27 06:24 UTC by dhanrajdc7

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #1085

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [x] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Certificate Sender

Folder: Certificate-Sender

Requirements: Pandas, Pillow, Openpyxl

Script: `main.py`

Arguments: Nil

Contributor: dhanrajdc7

Description: Send Bulk Certificates Automatically via Mail.

2021-05-28 14:17 UTC, kaustubhgupta requested changes
- PR template wrongly updated. Check approved PRs for reference.
- Delete the Data1.xlsx
- The readme file doesn't contain any good information about the script. Check other in the repo or approved PRs. 
- Other changes:

2021-05-28 14:17 UTC, kaustubhgupta commented on Certificate-Sender/main.py
> +body = """Hi!\n\nThanks for your active participation in our webinar on "All About Git, GitHub & Open Source"
Get this data from user via input functions

2021-05-28 14:17 UTC, kaustubhgupta commented on Certificate-Sender/main.py
> +excelFile = "Data.xlsx"  # DATA(NAME & EMAIL)
get the input for data file path from user

2021-05-31 02:03 UTC, kaustubhgupta commented
@dhanrajdc7 update the PR before 2 pm so that we can review the code and merge it timely

2021-05-31 06:49 UTC, dhanrajdc7 commented
@kaustubhgupta Pls review.

2021-05-31 11:28 UTC, kaustubhgupta requested changes
- Not deleted data1.xlsx
- Other changes:

2021-05-31 11:28 UTC, kaustubhgupta commented on Certificate-Sender/.env.sample
> +Also, don't forget to tag on LinkedIn with your certificate. we are happy to see you there!
I have clearly mentioned in this suggestion that takes these values as input from user via input function: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1131#discussion_r641585677

2021-05-31 11:28 UTC, kaustubhgupta commented on Certificate-Sender/.gitignore
> +*env/
not needed, you can remove this

2021-05-31 11:28 UTC, kaustubhgupta commented on Certificate-Sender/README.md
> +- Add all details in `.env` file
not valid

2021-05-31 11:28 UTC, kaustubhgupta commented on Certificate-Sender/main.py
> +    excel_file = os.getenv('CERTIFICATE_HOLDERS_EXCEL_FILEPATH')
what is this statement? Get the file path from user via input function

2021-05-31 11:28 UTC, kaustubhgupta commented on Certificate-Sender/main.py
> +            'CERTIFICATE_NAME_STARTING_POSITION').split(',')))
these inputs need to be obtained from user via input function

2021-05-31 11:28 UTC, kaustubhgupta commented on Certificate-Sender/main.py
> +        body = os.getenv('CERTIFICATE_EMAIL_BODY')
these too

2021-06-02 18:10 UTC, dhanrajdc7 commented
@kaustubhgupta 

I have pushed my code by testing & made it very simple for users. If I implement input() & let's say if the program crashes due to Gmail SMTP error (like Daily Limit), then the user will have to enter all details again to run it again. This bad user experience doesn't make any sense!!!! 

I have added Excel File to let know users about the Data format.

2021-06-02 18:21 UTC, kaustubhgupta commented
> @kaustubhgupta
> 
> I have pushed my code by testing & made it very simple for users. If I implement input() & let's say if the program crashes due to Gmail SMTP error (like Daily Limit), then the user will have to enter all details again to run it again. This bad user experience doesn't make any sense!!!!
> 
> I have added Excel File to let know users about the Data format.

We are making a master script where your program will be part of a pool of scripts. As soon as the master script is run and the user selects your script, how will the user provide the data? You can't instruct the user to close the master script, go back to the file directory, edit the .env file, and then run the master script! That's why you were told to make changes to the script to make it dynamic. The data format for excel can be explained in the readme file. 

Also, as the GSSOC period is over, only approved PRs will be merged and no new reviews/approvals would be made. You were told to make the changes two days back (31st May).

2021-06-08 07:24 UTC, closed without merging