Scraping Song
avinashkranjan/Amazing-Python-Scripts pull request #1136
Opened 2021-05-28 12:03 UTC by anumshka

# Description

Scraping Songs from and mailing the list.

## Fixes #1132

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [x] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [ ] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: ScrapingSongs

Folder: Scrapingsongs

Requirements: importing bs4,requests,smtplib,tabulate,MIMEText,MIMEMultipart

Script: ScrapingSongs.py

Arguments: None

Contributor: anumshka

Description: Scraping Songs from and mailing the list.

2021-05-28 14:26 UTC, kaustubhgupta requested changes

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/ScrapingSongs.py
> +response = requests.get("https://open.spotify.com/playlist/37i9dQZF1DX5KpP2LN299J")
get the URL from user

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/ScrapingSongs.py
> +data.to_csv("new_data.csv", index=False)
```suggestion
data.to_csv("./ScrapingSongs/new_data.csv", index=False)
```

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/ScrapingSongs.py
> +with open('new_data.csv', encoding='UTF-8') as input_file:
```suggestion
with open('./ScrapingSongs/new_data.csv', encoding='UTF-8') as input_file:
```

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/ScrapingSongs.py
> +    connection.sendmail(from_addr="sender_address", to_addrs="receiver_address", msg=message.as_string())
Do you think this will send any email?

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/new_data.csv
> +Wildest Dreams,https://open.spotify.com/track/3fVnlF4pGqWI9flVENcT28
delete this file

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/readme.md
> +# Package/Script Name
Is this the right heading for the readme file?

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/readme.md
> +It scrapes spotify data to collect famous Taylor Swift's songs and mails it to her fans.
Only Taylor swift and no other artists?

2021-05-28 14:26 UTC, kaustubhgupta commented on ScrapingSongs/readme.md
> +python file.py
do you have any file named `file.py` ?

2021-05-31 02:04 UTC, kaustubhgupta commented
@anumshka update the PR before 2 pm so that we can review the code and merge it on time

2021-06-07 09:24 UTC, avinashkranjan commented
Hey @anumshka are you going to update the PR..or Should I close it?

2021-06-12 06:33 UTC, closed without merging