added python script
avinashkranjan/Amazing-Python-Scripts pull request #1138
Opened 2021-05-28 19:19 UTC by aanshi18

# Description

Website Blocker Python Script

## Fixes #(#1129 )

Used to block all websites given as a list in the python script

## Type of change

- [.] New feature (non-breaking change which adds functionality)

## Checklist:

- [.] My code follows the style guidelines(Clean Code) of this project
- [.] I have performed a self-review of my own code
- [.] I have commented my code, particularly in hard-to-understand areas
- [.] I have created a helpful and easy to understand `README.md`
- [.] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [.] I have added the project meta data in the PR template.
- [.] I have created the ``requirements.txt`` file if needed.

## Project Metadata

Category:

- [.] Social_Media
- [.] OS_Utilities
- [.] Automation

Title: Website Blocker

Folder: Website-Blocker
Requirements: None

Script: website_blocker.py

Arguments: python website_blocker.py 

Contributor: aanshi18

Description: Used to block all websites given as a list in the python script

2021-05-30 15:59 UTC, santushtisharma10 commented
@kaustubhgupta i am unable to run the script on my local system, please check its working

2021-05-31 02:05 UTC, kaustubhgupta commented
> @kaustubhgupta i am unable to run the script on my local system, please check its working

sure

2021-05-31 02:07 UTC, kaustubhgupta requested changes

2021-05-31 02:07 UTC, kaustubhgupta commented on Website-Blocker/website_blocker.py
> +websites = [ "www.youtube.com", "twitter.com","www.skype.com/en", "www.facebook.com","www.instagram.com"]
take the websites input from user

2021-05-31 02:07 UTC, kaustubhgupta commented on Website-Blocker/website_blocker.py
> +end = dt(2021, 4, 24)
take this input from user

2021-05-31 02:07 UTC, kaustubhgupta commented on Website-Blocker/website_blocker.py
> +        break
how the logic is working? how the user is removing websites from blocked hosts?

2021-06-07 09:24 UTC, avinashkranjan commented
Hey @aanshi18  are you going to update the PR..or Should I close it?

2021-06-07 17:31 UTC, aanshi18 commented
Yes, I will update it within a day.

2021-06-08 03:59 UTC, aanshi18 commented
I have updated the script.

2021-06-12 06:36 UTC, kaustubhgupta requested changes

2021-06-12 06:36 UTC, kaustubhgupta commented on Website-Blocker/website_blocker.py
> +start_time = int(input("Enter the starting time:"))
```suggestion
start_time = int(input("Enter the starting time: "))
```

2021-06-12 06:36 UTC, kaustubhgupta commented on Website-Blocker/website_blocker.py
> +end_time = int(input("Enter the endin time: "))
```suggestion
end_time = int(input("Enter the ending time: "))
```

2021-06-12 06:36 UTC, kaustubhgupta commented on Website-Blocker/website_blocker.py
> +                if not any(website in line for website in website_list):
include the logic to unblock the websites

2021-06-22 05:02 UTC, closed without merging