Added YouTube Downloader application to this repo
avinashkranjan/Amazing-Python-Scripts pull request #1650
Opened 2023-06-04 03:58 UTC by TheKidPadra

I wrote a new approach YouTube downloader python application, I hope it's useful for this repo and gets merge
I learned a lot from this repo and I just wanted to make a contribution

# Description

I saw all these YouTube downloader around, and I just came up with a new idea, so I thought I could help. Also this is my first time making a real Contribution to a project so. 

## Type of change

_Please delete options that are not relevant._

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)

Category:
- [ ] Social_Media
- [ ] Automation
- [ ] Fun

Title: \<YouTube Downloader\>

Folder: \<Padra's YouTube Downloader\>

Requirements: \<YouTube_Donlowder.py\>

Script: \<YouTube_Donlowder.py\>

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: \<@TheKidPadra\>

Description: \<a new approach YouTube downloader python application\>

2023-06-09 05:00 UTC, avinashkranjan commented
Create an Issue, If not already Present and then Link the Issue to this PR.

2023-06-09 05:00 UTC, avinashkranjan requested changes
Add a `README` file and `requirements` file

2023-06-17 17:48 UTC, TheKidPadra commented
> Add a `README` file and `requirements` file

1: added the README file 
2:Since it doesn't need any requirement file, I just wrote libraries that user should install in my first comment
I listed them in README file as well 

I hope everything is complete, if it's not, help me to make this right

2023-06-28 06:21 UTC, avinashkranjan approved these changes

2023-06-28 06:21 UTC, merged