Added a .gitignore
avinashkranjan/Amazing-Python-Scripts pull request #180
Opened 2021-01-05 13:21 UTC by vybhav72954

# Description

I have added a `.gitignore` for this project.

I have covered
- JetBrains IDE
- vscode
- eclispe
- Jupyter
- virtualenv
- MacOS

along with the basic ignored files.

## Fixes #169 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-01-06 13:54 UTC, bismitaguha requested changes

2021-01-06 13:54 UTC, bismitaguha commented on .gitignore
> +.vs/
Should be .vscode I guess???

2021-01-07 11:45 UTC, avinashkranjan approved these changes
LGTM .💯

2021-01-07 11:46 UTC, merged

2021-01-07 11:46 UTC, avinashkranjan commented
@all-contributors please add @vybhav72954 for documentation