Added the folder whatsapp-automation containing all the files
avinashkranjan/Amazing-Python-Scripts pull request #203
Opened 2021-01-08 07:38 UTC by vaishnavirshah

# Description

This python script will allow the user to send whatsapp messages through it.
In this script the user is asked to :
- Mention the name of the user they want to send the message to
- Write the message they want to send
- And scan for whatsapp web.
-And then the message will be automatically sent to that user. 

## Fixes #188 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-01-08 12:04 UTC, bismitaguha requested changes

2021-01-08 12:04 UTC, bismitaguha commented on Whatsapp_Automation/whatsappAutomation.py
> +        sendbutton.click()
Print a response here on successful message sent action. You could add try catch here!!

2021-01-10 05:51 UTC, avinashkranjan approved these changes
LGTM..💯

2021-01-10 05:51 UTC, merged

2021-01-10 05:52 UTC, avinashkranjan commented
@all-contributors please add @vaishnavirshah  for code and documentation