Keep Mouse Active
avinashkranjan/Amazing-Python-Scripts pull request #2058
Opened 2023-07-03 07:43 UTC by akshaykhoje

# Description

This directory contains a python script to keep the mouse moving to avoid the screen going black in case you want to keep it on all the time.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have added the project meta data in the PR template.
- [ ] I have created the ``requirements.txt`` file if needed.

Category:
- [ ] Automation

Title: Keep Mouse Active

Folder: Move-Mouse

Requirements: requirements.txt

Script: move.py

Contributor: akshaykhoje

Description: Keep the screen going on to avoid it turning off.

2023-07-06 07:43 UTC, avinashkranjan requested changes
Mention the Issue number

2023-07-22 02:00 UTC, JRudransh commented on Move-Mouse/move.py
> +import time
Remove unused imports

2023-07-22 02:09 UTC, JRudransh commented on Move-Mouse/move.py
This program is very dangerous, If user is trying to use his mouse, you are not allowing to do it. That should be handeled correctly.

What you can do:
1. Save the initial cursor position
2. When user try to use his cursor (At the time user moves the cursor) restore the cursor initial position and halt
3. Keep track on mouse or keyboard activity
4. If you dont see any activity for `x` amount of time, resume the program

2023-07-22 02:13 UTC, JRudransh requested changes
This program is overriding user's cursor movement. Please act upon my comment

2023-07-30 15:59 UTC, akshaykhoje commented
> This program is overriding user's cursor movement. Please act upon my comment

I apologise for my inactivity. I have been occupied with a couple of heavy projects lately. 

I will try doing the mentioned changes as soon as possible.

Thanks for your inputs @JRudransh.

2023-07-30 15:59 UTC, akshaykhoje commented on Move-Mouse/move.py
Yup will work on it.

2023-08-26 01:47 UTC, closed without merging