Created a scrabble game
avinashkranjan/Amazing-Python-Scripts pull request #2175
Opened 2023-07-09 03:45 UTC by nashira26

# Description

Added the script for a scrabble game which can be played between multiple players.

## Fixes #1580

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [ x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] I have added the project meta data in the PR template.
- [x] I have created the ``requirements.txt`` file if needed.

## Project Metadata

`` If there is no-file/nothing to fill the below fields with, then type: none ``

`` Example: `` If no requirements.txt needed/present, then type none in ``Requirments``.

Category:
- [ ] Calculators
- [ ] AI/ML
- [ ] Scrappers
- [ ] Social_Media
- [ ] PDF
- [ ] Image_Processing
- [ ] Video_Processing
- [x] Games
- [ ] Networking
- [ ] OS_Utilities
- [ ] Automation
- [ ] Cryptography
- [ ] Computer_Vision
- [ ] Fun
- [ ] Others

Title: Scrabble

Folder: scrabble

Requirements: requirements.txt

Script: scrabble.py

Arguments: \<enter any arguments that the script needs but `-` separeted like: h-c-m\>

Contributor: nashira26
Description: The script for a scrabble game which can be played between multiple players.

2023-07-21 08:07 UTC, nashira26 commented
I have updated the folder as per requested. Please review.

2023-07-21 08:30 UTC, avinashkranjan requested changes
`.gitmodules` is still in root directory

2023-07-21 09:10 UTC, nashira26 commented
It is resolved now. Please check

2023-07-30 06:14 UTC, avinashkranjan approved these changes

2023-07-30 06:15 UTC, merged