Snake game using Python
avinashkranjan/Amazing-Python-Scripts pull request #306
Opened 2021-01-28 12:37 UTC by CharvyJain

# Description

Added the Script of Snake Game using Pygame

## Fixes #295

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

2021-01-28 13:00 UTC, ShristiJalan approved these changes

2021-01-28 17:48 UTC, avinashkranjan requested changes
Rest LGTM..🚀

2021-01-28 17:48 UTC, avinashkranjan commented on Snake Game (GUI)/README.md
> +![Snake Game](game.png)
Add Image Rather than link

2021-01-29 08:06 UTC, atarax665 approved these changes

2021-01-29 11:03 UTC, CharvyJain commented on Snake Game (GUI)/README.md
> +![Snake Game](game.png)
Sorry, I didn't get you!

2021-01-31 11:52 UTC, avinashkranjan approved these changes

2021-01-31 11:52 UTC, merged

2021-01-31 11:52 UTC, avinashkranjan commented
@all-contributors please add @CharvyJain  for code and documentation