Added typing speed test
avinashkranjan/Amazing-Python-Scripts pull request #382
Opened 2021-02-17 21:33 UTC by abhishek-iiit

# Description

Added Typing speed test

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ x ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ x ] My code follows the style guidelines(Clean Code) of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have created a helpful and easy to understand `README.md`
- [ x ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ x ] My changes generate no new warnings
- [ x ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-02-17 21:37 UTC, abhishek-iiit commented
Made within SWOC

2021-02-24 10:55 UTC, avinashkranjan requested changes
Add a Issue for the Same

2021-02-24 16:59 UTC, atarax665 requested changes

2021-02-24 16:59 UTC, atarax665 commented on typing speed test/linter.yml
> +---
What is the use of super linter in typing speed test project?

2021-02-24 16:59 UTC, atarax665 commented on typing speed test/main.py
> +        self.image_open = pygame.image.load(os.path.abspath("/home/abhishek/Desktop/GITHUB/SWOC/Amazing-Python-Scripts/typing speed test/typing_speed.png"))
The image path should be edited accordingly when the project is cloned on the local machine. Please do mention this here as in-code comment and also mention it in the README.

2021-02-24 16:59 UTC, atarax665 commented on typing speed test/readme.md
> +before running the scipt,
Include all the steps from cloning this repo to running the main.py file.

2021-02-24 16:59 UTC, atarax665 commented on typing speed test/readme.md
> +Attached in the file named 'screenshot.png'
Add output image link here.

2021-03-01 03:51 UTC, closed without merging