Add whatsapp bot
avinashkranjan/Amazing-Python-Scripts pull request #453
Opened 2021-03-07 17:56 UTC by muthuannamalai12

# Description
I have added a Whatsapp Bot which performs the following task
To automatically send a message to a group of people individually.
To schedule your message
Voice Controlled Bot
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #451 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-12 05:30 UTC, kaustubhgupta commented
@muthuannamalai12 kindly check the code so that all the test pass and after that your PR will be reviewed

2021-03-12 13:19 UTC, kaustubhgupta commented
To pass the Lint tests, Kindly do the following:
- download autopep8 using pip
- Go to your project directory.
- Run the command: 
    ```bash 
       autopep8 -i -r --verbose ./
    ```

This should help you pass the test

2021-03-14 03:38 UTC, kaustubhgupta commented
updates @muthuannamalai12 ?

2021-03-14 03:54 UTC, muthuannamalai12 commented
> updates @muthuannamalai12 ?

I will complete it within tomorrow

2021-03-14 03:56 UTC, kaustubhgupta commented
@muthuannamalai12 and the insta bot?

2021-03-14 04:00 UTC, muthuannamalai12 commented
> @muthuannamalai12 and the insta bot?

I will complete Insta Bot also within tomorrow.

2021-03-15 14:41 UTC, muthuannamalai12 commented
> To pass the Lint tests, Kindly do the following:
> 
> * download autopep8 using pip
> * Go to your project directory.
> * Run the command:
>   ```shell
>      autopep8 -i -r --verbose ./
>   ```
> 
> This should help you pass the test

I have done it still the error is present

2021-03-15 14:44 UTC, muthuannamalai12 commented
![image](https://user-images.githubusercontent.com/64524822/111171499-fe397b00-85ca-11eb-92c6-06562e19574a.png)

After I apply the command it shows 0 error is present

2021-03-15 14:47 UTC, kaustubhgupta requested changes
I got your error and you will be shocked what was your mistake:

2021-03-15 14:47 UTC, kaustubhgupta commented on whatsapp-bot/whatsapp-bot.py
> +from Voice_control_Module.py import *
```suggestion
from Voice_control_Module import *
```

2021-03-15 15:01 UTC, muthuannamalai12 commented
I have updated it @kaustubhgupta

2021-03-15 17:03 UTC, muthuannamalai12 commented
I have updated @kaustubhgupta. Kindly review again

2021-03-16 06:20 UTC, kaustubhgupta reviewed
I am not able to run this bot locally, @antrikshmisri @santushtisharma10 can you confirm if this working or not?
![image](https://user-images.githubusercontent.com/43691873/111263993-cb37cb80-864c-11eb-93b0-88ed5ef87478.png)

2021-03-18 03:34 UTC, kaustubhgupta commented
@muthuannamalai12 you haven't responded about this in 2 days. I can give you the last 6 Hrs to fix this after that this PR will be closed.

2021-03-18 03:46 UTC, kaustubhgupta requested changes
Did you ran this script? There are a lot of bugs here:
- There is not purpose of CSV file as you have not used the loadContacts function anywhere
- You are taking the user input as user_name but in the send message function, it is phone number list.

2021-03-18 03:47 UTC, kaustubhgupta commented
@muthuannamalai12 I can give you the last 6 Hrs to fix these issues after that this PR will be closed.

2021-03-18 03:50 UTC, muthuannamalai12 commented
> @muthuannamalai12 I can give you the last 6 Hrs to fix these issues after that this PR will be closed.

I have been trying to correct it I will do my level best If I cannot make it I will close the Pull Request

2021-03-18 03:51 UTC, kaustubhgupta commented
> > @muthuannamalai12 I can give you the last 6 Hrs to fix these issues after that this PR will be closed.
> 
> I have been trying to correct it I will do my level best If I cannot make it I will close the Pull Request

This script is not even running for one case, didn't you tested this before pushing the code?

2021-03-19 05:49 UTC, kaustubhgupta commented
@muthuannamalai12 Please update the final status?

2021-03-19 05:51 UTC, muthuannamalai12 commented
> @muthuannamalai12 Please update the final status?

I tried my best but cannot solve the bug

2021-03-19 05:54 UTC, kaustubhgupta commented
@muthuannamalai12 Okay no issues, you can work on the other two newly assigned issues. These two (Whatsapp bot and insta bot) will be assigned to someone else

2021-03-19 05:54 UTC, closed without merging