add(Script): IMDB Scraper
avinashkranjan/Amazing-Python-Scripts pull request #470
Opened 2021-03-10 07:24 UTC by priyanshu20

closes #311 

## Modules Used

- requests
- bs4 (BeautifuSoup)
- argparse

<hr>

## How it works

- The User provides a query title and the script scrapes the IMDB website for data on it

- Since IMDB provides 200 results for every query, the data of top 5 is scraped, this is easily configurable.

## Usage

- Install dependencies
- python scraper.py --t movie-name-here
- sample : python scraper.py --t red
## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-12 10:01 UTC, santushtisharma10 commented
@kaustubhgupta @tamanna-verma @antrikshmisri

2021-03-12 12:35 UTC, antrikshmisri commented
> @kaustubhgupta @tamanna-verma @antrikshmisri

Although there is a similar [script](https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Movie-Recommendation). I think this can be added

2021-03-12 12:35 UTC, antrikshmisri approved these changes

2021-03-12 13:10 UTC, kaustubhgupta requested changes

2021-03-12 13:10 UTC, kaustubhgupta commented on IMDB-Scraper/README.md
> +- python scraper.py --t movie-name-here
```suggestion
- python scraper.py --t movie-name-here (in double quotes)
```

2021-03-12 13:10 UTC, kaustubhgupta commented on IMDB-Scraper/README.md
> +- sample : python scraper.py --t red
```suggestion
- sample : python scraper.py --t "red"
```

2021-03-12 13:10 UTC, kaustubhgupta commented on IMDB-Scraper/scraper.py
> +import requests
![image](https://user-images.githubusercontent.com/43691873/110943815-a946fc00-8361-11eb-8348-a77d41784c9b.png)
The output has several issues:
- Printing "Something went wrong" which should not be printed as it breaks the flow of reading.
- Look at Highlighted in yellow: it is printing non extra characters. (\xa0)
- You should not print entries which are not complete as it only floods the terminal. Only display values which are somewhat complete.

2021-03-12 16:07 UTC, antrikshmisri requested changes
This should fix the `Something went wrong` exception being printed on each iteration.

2021-03-12 16:07 UTC, antrikshmisri commented on IMDB-Scraper/scraper.py
> +    info = {}
```suggestion
    info = {}
    labels = ['title', 'year', 'rating', 'genre', 'plot',
              'country', 'date', 'budget', 'gross_USA', 'gross_worldwide']
```

2021-03-12 16:07 UTC, antrikshmisri commented on IMDB-Scraper/scraper.py
> +        print("Something went wrong")
```suggestion
        assert any(obj in labels for obj in info),"No info found"
```

2021-03-12 16:35 UTC, kaustubhgupta commented
@antrikshmisri Good suggestions 💯

2021-03-12 19:27 UTC, priyanshu20 commented
Thank you everyone for your feedback I have made the necessary changes.
Requesting a re review from @kaustubhgupta  and @antrikshmisri

2021-03-13 04:50 UTC, kaustubhgupta approved these changes
Now it's good!

2021-03-14 22:25 UTC, avinashkranjan approved these changes

2021-03-14 22:26 UTC, merged

2021-03-14 22:27 UTC, avinashkranjan commented
@all-contributors please add @priyanshu20 for code and documentation