Spreadsheet Automation
avinashkranjan/Amazing-Python-Scripts pull request #502
Opened 2021-03-11 14:52 UTC by Amit366

# Description

The script will compare two spreadsheets and then show a pie chart

## Fixes #469

2021-03-11 14:53 UTC, Amit366 commented
@avinashkranjan please add the level tag

2021-03-11 18:47 UTC, antrikshmisri requested changes
@Amit366 Please add a README.md with instruction on how to run the script

2021-03-12 08:21 UTC, antrikshmisri approved these changes
Approved from my side. @kaustubhgupta please add the tags

2021-03-12 12:49 UTC, kaustubhgupta requested changes
This is not a generalized script. What happens if I select totally different datasets that do not have "Total Price" and "Purchased Amount" columns? Here is the solution to this:

- Make it a CLI version where the user mentions the dataset 1 column to be compared and the same for dataset 2. 
- Take the input for the common column where the merger will happen.
- Now display the plots

2021-03-12 16:22 UTC, Amit366 commented
@kaustubhgupta sir I have updated it

2021-03-12 16:32 UTC, kaustubhgupta requested changes

2021-03-12 16:32 UTC, kaustubhgupta commented on Spreadsheet_Automation/script.py
> +data_total['Total Price'] = data_total['PURCHASED AMOUNT'] * data_total['Price']
This line is not required I think?

2021-03-12 16:32 UTC, kaustubhgupta commented on Spreadsheet_Automation/script.py
> +material=input("Enter criteria 1")
name the variables with descriptive meaning. Suggestion:
```suggestion
criteria_1=input("Enter criteria 1")
```

2021-03-12 16:32 UTC, kaustubhgupta commented on Spreadsheet_Automation/script.py
> +fig = px.pie(data_total[[material, price]], values=price, names=material)
Update the changes here also

2021-03-12 16:46 UTC, Amit366 commented
@kaustubhgupta now check

2021-03-12 16:52 UTC, kaustubhgupta requested changes
Sorry I didn't notice these variables earlier:

2021-03-12 16:52 UTC, kaustubhgupta commented on Spreadsheet_Automation/script.py
> +book_relative_path = input("Enter first dataset")
These two datasets names also need to be changed to something good.

2021-03-12 16:52 UTC, kaustubhgupta commented on Spreadsheet_Automation/script.py
> +data_prices = pd.read_excel(book_prices)
Here also

2021-03-12 16:52 UTC, kaustubhgupta commented on Spreadsheet_Automation/script.py
> +item = input("What is the basis of merging? ")
And this item too.

2021-03-13 15:31 UTC, Amit366 commented
@avinashkranjan updated

2021-03-13 15:32 UTC, kaustubhgupta approved these changes

2021-03-13 15:33 UTC, kaustubhgupta commented
@santushtisharma10 your approval awaited

2021-03-13 19:04 UTC, santushtisharma10 approved these changes

2021-03-14 22:42 UTC, merged

2021-03-14 22:42 UTC, avinashkranjan commented
@all-contributors please add @Amit366  for code and documentation