Added DP downloader
avinashkranjan/Amazing-Python-Scripts pull request #511
Opened 2021-03-11 18:47 UTC by sudipg4112001

### Issue fixed
Fixes #468 

Please review the PR

2021-03-12 17:35 UTC, kaustubhgupta requested changes

2021-03-12 17:35 UTC, kaustubhgupta commented on WhatsApp_DP_download/readme.md
> +### This, is a gist of this project..!!
This line is not needed

2021-03-12 17:35 UTC, kaustubhgupta commented on WhatsApp_DP_download/profile_pic_download.py
> +# region IMPORTS
Remove these region comments from the script

2021-03-13 04:11 UTC, sudipg4112001 commented
I have made the changes. Please review

2021-03-13 05:01 UTC, kaustubhgupta requested changes

2021-03-13 05:01 UTC, kaustubhgupta commented on WhatsApp_DP_download/profile_pic_download.py
> +
Remove extra spaces from the program

2021-03-13 05:01 UTC, kaustubhgupta commented on WhatsApp_DP_download/readme.md
> +### This, is a gist of this project..!!
I said to remove this line: "### This, is a gist of this project..!!" and not the above text. Bring back that text and remove this

2021-03-13 05:49 UTC, sudipg4112001 commented
I don't think the extra spaces in the program effects the program. Rather, it separates the program into different parts, which indicates different working. But, if you want I can do. But, if it is kept it will be beneficial.

2021-03-13 05:49 UTC, sudipg4112001 commented
And, I have done the changes in the readme

2021-03-13 05:55 UTC, kaustubhgupta commented
> I don't think the extra spaces in the program effects the program. Rather, it separates the program into different parts, which indicates different working. But, if you want I can do. But, if it is kept it will be beneficial.

I also had this same thought process until I read this thread last year, maybe it clears your doubts! https://softwareengineering.stackexchange.com/questions/251216/is-too-much-whitespace-a-bad-thing

2021-03-13 06:01 UTC, sudipg4112001 commented
Okay.. I will make the required changes. 
I need some time.

2021-03-14 03:50 UTC, kaustubhgupta commented
@sudipg4112001 updates?

2021-03-14 04:59 UTC, sudipg4112001 commented
> @sudipg4112001 updates?

Actually, I am facing some issues with my device. So, I need 2/3 days time.

2021-03-14 05:57 UTC, kaustubhgupta commented
> > @sudipg4112001 updates?
> 
> Actually, I am facing some issues with my device. So, I need 2/3 days time.

I can give time for today only

2021-03-15 08:34 UTC, kaustubhgupta commented
No response from your side, this PR has been closed

2021-03-15 08:34 UTC, closed without merging