Added Dice roll simulator
avinashkranjan/Amazing-Python-Scripts pull request #517
Opened 2021-03-12 13:37 UTC by mehabhalodiya

# Description

We will need to import these modules:
- Tkinter: Imported to use Tkinter and make GUI applications.
- Image, Imagetk: Imported from PIL, i.e. Python Imaging Library. We use it to perform operations involving images in our UI.
- Random: Imported to generate random numbers.

## Fixes #439 Dice Rolling Simulator

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-13 07:27 UTC, santushtisharma10 approved these changes

2021-03-13 07:28 UTC, santushtisharma10 commented
@kaustubhgupta @antrikshmisri @tamanna-verma

2021-03-13 07:45 UTC, kaustubhgupta requested changes
@mehabhalodiya You again messed the image paths

2021-03-13 07:45 UTC, kaustubhgupta commented on Dice-Roll-Simulator/dice_roll_simulator.py
> +dice = ['die1.png', 'die2.png', 'die3.png', 'die4.png', 'die5.png', 'die6.png']
```suggestion
dice = ['./Dice-Roll-Simulator/imgs/die1.png', './Dice-Roll-Simulator/imgs/die2.png', './Dice-Roll-Simulator/imgs/die3.png', './Dice-Roll-Simulator/imgs/die4.png', './Dice-Roll-Simulator/imgs/die5.png', './Dice-Roll-Simulator/imgs/die6.png']
```

2021-03-13 08:31 UTC, antrikshmisri commented on Dice-Roll-Simulator/dice_roll_simulator.py
> +dice = ['die1.png', 'die2.png', 'die3.png', 'die4.png', 'die5.png', 'die6.png']
Or could even use list comprehension
```suggestion
dice_names = ['die1.png', 'die2.png', 'die3.png', 'die4.png', 'die5.png', 'die6.png']
dice_path = [os.path.join(os.getcwd() , 'imgs' , ele) for ele in dice_names]
```

2021-03-13 14:38 UTC, kaustubhgupta approved these changes

2021-03-13 14:38 UTC, kaustubhgupta commented
@antrikshmisri

2021-03-13 14:41 UTC, antrikshmisri approved these changes
LGTM 💯

2021-03-14 22:45 UTC, avinashkranjan approved these changes

2021-03-14 22:45 UTC, merged