Extracting text from a real time captured image (#497)
avinashkranjan/Amazing-Python-Scripts pull request #527
Opened 2021-03-12 20:07 UTC by ShubhamGupta577

# Description

In this script, we are going to read a real-time captured image using a webcam or any other camera and extract the text from that image by removing noise from it.
This script uses `OpenCV` for capturing the real-time image and `pytesseract` for text extraction from the captured image.
Here I added two types of files as one `.py` which can be used on a machine and the other is with the `.ipynb` extension so that it can be used on google colab which removes the need for external installation.

## Fixes #497 
Extracting the text from a real-time captured image. (GSSOC'21)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings

2021-03-13 14:08 UTC, ShubhamGupta577 commented
@kaustubhgupta Please review it.

2021-03-13 15:02 UTC, kaustubhgupta approved these changes

2021-03-13 15:03 UTC, kaustubhgupta requested changes

2021-03-13 15:03 UTC, kaustubhgupta commented on Realtime Text Extraction/Realtime Text Extraction.py
> +pytesseract.pytesseract.tesseract_cmd = r"C:\Users\91769\AppData\Local\Programs\Tesseract-OCR\tesseract.exe"
Take the input for pytesseract path

2021-03-13 15:03 UTC, kaustubhgupta commented on Realtime Text Extraction/Realtime Text Extraction.py
> +        path=r'C:\Users\91769\Desktop\images'+'\img.jpg'
take this path as input

2021-03-13 15:03 UTC, kaustubhgupta commented on Realtime Text Extraction/Realtime Text Extraction.py
> +src= Image.open(r"C:\Users\91769\Desktop\images\img.jpg")
this also

2021-03-13 18:54 UTC, ShubhamGupta577 commented
@kaustubhgupta Required changes have been made. Please review them.

2021-03-14 03:08 UTC, kaustubhgupta approved these changes

2021-03-14 03:09 UTC, kaustubhgupta commented
@santushtisharma10 @antrikshmisri

2021-03-14 06:48 UTC, antrikshmisri approved these changes

2021-03-14 22:52 UTC, avinashkranjan approved these changes
LGTM..🚩

2021-03-14 22:52 UTC, merged

2021-03-14 22:53 UTC, avinashkranjan commented
@all-contributors please add @ShubhamGupta577  for code and documentation