Translator python
avinashkranjan/Amazing-Python-Scripts pull request #538
Opened 2021-03-13 06:15 UTC by NEERAJAP2001

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #484 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-13 13:31 UTC, antrikshmisri requested changes
Instead of hardcoding the text and language take the inputs from the user. Also, I was not able to execute the code due to dependency issues. @kaustubhgupta @santushtisharma10 @tamanna-verma , can someone confirm if the code runs.

2021-03-13 14:38 UTC, NEERAJAP2001 commented
Alright, @antrikshmisri  changes coming up !! 

> Also, I was not able to execute the code due to dependency issues.

Please read the documentation, I've mentioned dependencies there!
Thanks

2021-03-13 14:45 UTC, antrikshmisri commented
> Alright, @antrikshmisri changes coming up !!
> 
> > Also, I was not able to execute the code due to dependency issues.
> 
> Please read the documentation, I've mentioned dependencies there!
> Thanks

@NEERAJAP2001 I meant  I wasn't able to run the code with the mentioned dependencies on my local machine

2021-03-14 04:06 UTC, kaustubhgupta requested changes

2021-03-14 04:06 UTC, kaustubhgupta commented on Translator Script/Translation.py
> +
Remove the unnecessary blank lines and comments. It's 6 lines code and it will remain that only

2021-03-14 09:21 UTC, NEERAJAP2001 commented
![Screenshot (254)](https://user-images.githubusercontent.com/65017645/111063463-93a61380-84d4-11eb-9815-0ff98d59c7fb.png)


@kaustubhgupta Works Fine!!

2021-03-14 09:47 UTC, kaustubhgupta requested changes

2021-03-14 09:47 UTC, kaustubhgupta commented on Translator Script/Translation.py
> +# First Step : Go to cmd and type: pip install googletrans==3.1.0a0
This first line is not needed as it is already mentioned in the README.md file dependency section

2021-03-14 10:23 UTC, kaustubhgupta approved these changes

2021-03-14 10:23 UTC, kaustubhgupta commented
@santushtisharma10 approval awaited

2021-03-14 13:59 UTC, antrikshmisri approved these changes

2021-03-14 14:09 UTC, santushtisharma10 approved these changes

2021-03-14 22:55 UTC, avinashkranjan approved these changes

2021-03-14 22:55 UTC, merged

2021-03-14 22:55 UTC, avinashkranjan commented
@all-contributors please add @NEERAJAP2001  for code and documentation