add-flipkart-price-alert-with-changes
avinashkranjan/Amazing-Python-Scripts pull request #555
Opened 2021-03-14 08:13 UTC by Jade9ja

# Description

Added the flipkart price alert script.

## Fixes #541 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [X] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-14 10:18 UTC, kaustubhgupta requested changes
The code is well written, just a few minor changes:

2021-03-14 10:18 UTC, kaustubhgupta commented on Flipkart-price-alert/README.md
> +## How to get app password
It's confusing to write "app passwords". I would suggest rewriting it as "Optional: How to get alternate login credentials"

2021-03-14 10:18 UTC, kaustubhgupta commented on Flipkart-price-alert/README.md
> +# Setup Instructions
All heading levels after the "# Flipkart Price alert" heading need to be on the same level. Either make them (##) or (#)

2021-03-14 10:18 UTC, kaustubhgupta commented on Flipkart-price-alert/README.md
> +1) Edit the config vars in the track.py script.
This line is not needed any more

2021-03-14 10:18 UTC, kaustubhgupta commented on Flipkart-price-alert/track.py
> +MY_APP_PASSWORD = input('Enter the app password (Check readme for steps to generate app passwords):')
```suggestion
MY_APP_PASSWORD = input('Enter password:')
```

2021-03-15 09:26 UTC, kaustubhgupta approved these changes

2021-03-15 09:27 UTC, kaustubhgupta commented
@antrikshmisri @santushtisharma10

2021-03-15 15:02 UTC, santushtisharma10 commented
LGTM 💯

2021-03-15 15:03 UTC, santushtisharma10 approved these changes

2021-03-15 15:11 UTC, antrikshmisri approved these changes
LGTM 🚀

2021-03-18 20:57 UTC, avinashkranjan approved these changes
LGTM..

2021-03-18 20:57 UTC, merged