Salary predictor, issue no.-#507
avinashkranjan/Amazing-Python-Scripts pull request #556
Opened 2021-03-14 10:32 UTC by shreyasZ10

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #507

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-15 09:58 UTC, kaustubhgupta requested changes

2021-03-15 09:58 UTC, kaustubhgupta commented on Salary Predictor/model.py
> +df = pd.read_csv('dataset/cleaned_dataset.csv')
```suggestion
df = pd.read_csv('./Salary Predictor/dataset/cleaned_dataset.csv')
```

2021-03-15 09:58 UTC, kaustubhgupta commented on Salary Predictor/script.py
> +with open('models/random_forest2_model.sav', 'rb') as f:
Load model and columns at the beginning of the script. Also, fix the path of the model and columns as suggested in datasets.csv

2021-03-15 09:58 UTC, kaustubhgupta commented on Salary Predictor/script.py
> +   regressor = pickle.load(f)
The model is a random forest and you are saving it as a regressor? It may create confusion

2021-03-15 09:58 UTC, kaustubhgupta commented on Salary Predictor/script.py
> +
It is asking "Enter the sector of work" in the job profile selection also. Fix it
![image](https://user-images.githubusercontent.com/43691873/111135433-a9820a00-85a2-11eb-9001-1a235157a0c6.png)

2021-03-15 09:58 UTC, kaustubhgupta commented on Salary Predictor/README.md
> +
Remove the extra line here. Only 2 blank lines gap is enough

2021-03-16 08:52 UTC, kaustubhgupta requested changes
This will not work
```python
with open('../Salary Predictor/models/random_forest2_model.sav', 'rb') as f:
   random_forest_model = pickle.load(f)
```

This will: 
```python
with open('./Salary Predictor/models/random_forest2_model.sav', 'rb') as f:
   random_forest_model = pickle.load(f)
```

Kindly fix it in every path in model.py and script.py

2021-03-16 09:46 UTC, kaustubhgupta approved these changes
@shreyasZ10 Good Job 💯 💯!

2021-03-18 03:56 UTC, kaustubhgupta commented
@antrikshmisri @santushtisharma10 have a look at this PR

2021-03-18 14:21 UTC, santushtisharma10 approved these changes
LGTM  💯

2021-03-20 16:16 UTC, merged