Cartooning Image
avinashkranjan/Amazing-Python-Scripts pull request #597
Opened 2021-03-15 15:05 UTC by aliya-rahmani

Cartooning image using OpenCV issue #559

2021-03-16 10:03 UTC, kaustubhgupta requested changes
Add readme of the script along with these changes:

2021-03-16 10:03 UTC, kaustubhgupta commented on Crossword Solver/xword.py
> +#!/usr/bin/env python
Delete this file, it's not related to the current issue.

2021-03-16 10:03 UTC, kaustubhgupta commented on Cartooning Image/cartooneffect.py
> +img = cv2.imread("koala.jpeg")
Take the input of the file name from the user (Full path)

2021-03-16 13:25 UTC, kaustubhgupta requested changes
Did you run the script after updating it? Also delete the file requested and add readme file

2021-03-17 06:13 UTC, kaustubhgupta requested changes

2021-03-17 06:13 UTC, kaustubhgupta commented on Cartooning Image/README.md
> +# Cartooning Image with OpenCV
After this heading, maintain the levels of all subheadings as (##)

2021-03-18 07:12 UTC, kaustubhgupta approved these changes

2021-03-18 07:17 UTC, antrikshmisri approved these changes
LGTM 👍🏻

2021-03-18 11:31 UTC, santushtisharma10 approved these changes

2021-03-18 11:44 UTC, aliya-rahmani commented
@kaustubhgupta, Thanks for guiding me all the way!

2021-03-18 21:00 UTC, avinashkranjan approved these changes
LGTM..

2021-03-18 21:00 UTC, merged