Added Automatic Instagram Profile Pic Download
avinashkranjan/Amazing-Python-Scripts pull request #62
Opened 2020-10-03 17:10 UTC by hardikkhurana

It can be used easily by just inputting the username of the account

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2020-10-03 17:12 UTC, hardikkhurana commented
Thank you for giving me this chance I hope you like my work.

2020-10-03 17:17 UTC, avinashkranjan commented
@hardikkhurana Kindly fix syntax error, Before making a PR check the script on your system once
![ApplicationFrameHost_C1k7pWBX1e](https://user-images.githubusercontent.com/55796944/94997634-1c399300-05ca-11eb-9052-6eab1925f0cf.png)

And Few More things...
- Add a Readme file. 
- Attach a SS which shows working of your script.

2020-10-03 17:18 UTC, avinashkranjan requested changes
Make the Changes Mentioned

2020-10-03 17:18 UTC, avinashkranjan commented on Instagram Profile Pic Downloader/Instagram Profile Pic Downloader.py
> +print(x.download profile(username, profile pic_only=True))
Correct this syntax error

2020-10-03 17:44 UTC, hardikkhurana commented
I have solved all the errors and added SS also the readme file.

Thank You

2020-10-03 18:53 UTC, hardikkhurana commented
@avinashkranjan Sir, have you checked my new PR?or is there any problem from my side?

2020-10-03 18:58 UTC, avinashkranjan commented
@hardikkhurana I'm still looking into it...
![ApplicationFrameHost_81sGITn3qi](https://user-images.githubusercontent.com/55796944/94999650-78a3af00-05d8-11eb-9c45-fff7a69eebc4.png)
Your scripts run but does nothing..

2020-10-03 19:05 UTC, hardikkhurana commented
@avinashkranjan Sir A new folder will be created after you run the script in the same folder as the python script is stored in and in that folder there will be the profile pictures as i have also showed in the Screenshots

2020-10-03 19:11 UTC, avinashkranjan commented
@hardikkhurana No new Folder created.. Here the proof
![explorer_joJvTVxYIZ](https://user-images.githubusercontent.com/55796944/94999910-4dba5a80-05da-11eb-96c4-7189e7218518.png)

2020-10-03 19:25 UTC, hardikkhurana commented
@avinashkranjan I understand sir and would like to share this screen recorded video
here I am using Anaconda and Spyder

https://www.dropbox.com/s/v1rdwhua91pi3bc/Insta%20profile%20pic.mp4?dl=0

this is the link to that dropbox video 

Thank you

2020-10-03 19:28 UTC, avinashkranjan commented
> @hardikkhurana I'm still looking into it...
@hardikkhurana I knw..I think it's a problem from my side.... That's why I said..I'm currently looking into it..! Once it gets resolved I'll merge your PR

2020-10-04 07:30 UTC, avinashkranjan approved these changes
LGTM...💯

2020-10-04 07:30 UTC, merged

2020-10-04 07:31 UTC, avinashkranjan commented
@all-contributors please add @hardikkhurana for code and documentation