Price Comparison and Checker
avinashkranjan/Amazing-Python-Scripts pull request #637
Opened 2021-03-17 17:37 UTC by aashishah

# Description

The python script automatically searches for an item across Amazon, Flipkart and other online shopping websites and after performing comparisons, finds the cheapest price available.

## Fixes #545 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-18 05:53 UTC, kaustubhgupta requested changes
The code is working fine just some minor changes:

2021-03-18 05:53 UTC, kaustubhgupta commented on Price Comparison and Checker/Readme.md
> +##[Aashi Shah](https://github.com/aashishah)
```suggestion
## [Aashi Shah](https://github.com/aashishah)
```

2021-03-18 05:53 UTC, kaustubhgupta commented on Price Comparison and Checker/Requirements.txt
> +##Modules used in the program
This line is not needed. Also, rename the file to requirements.txt

2021-03-18 06:34 UTC, antrikshmisri commented on Price Comparison and Checker/price_comparison.py
> +item = input("Enter the item you would like to search for: ")
```suggestion
if __name__ == "__main__":
    item = input("Enter the item you would like to search for: ")
```

2021-03-18 06:43 UTC, antrikshmisri requested changes

2021-03-18 06:43 UTC, antrikshmisri commented on Price Comparison and Checker/price_comparison.py
> +item = input("Enter the item you would like to search for: ")
wrap everything from line `96` to `104` in this if statement. If you try to import this file in any other file the functions in line `97`,`98`,`99` will run immediately if not wrapped in this if statement.

2021-03-18 06:44 UTC, antrikshmisri requested changes

2021-03-18 06:44 UTC, antrikshmisri commented on Price Comparison and Checker/price_comparison.py
> +item = input("Enter the item you would like to search for: ")
```suggestion
if __name__ == "__main__":
    item = input("Enter the item you would like to search for: ")
```

2021-03-18 06:44 UTC, antrikshmisri commented on Price Comparison and Checker/price_comparison.py
> +item = input("Enter the item you would like to search for: ")
wrap everything from line `96` to `104` in this if statement. If you try to import this file in any other file the functions in line `97`,`98`,`99` will run immediately if not wrapped in this if statement.

2021-03-18 13:46 UTC, aashishah commented on Price Comparison and Checker/Readme.md
> +##[Aashi Shah](https://github.com/aashishah)
Made the changes. Please check.

2021-03-18 13:46 UTC, aashishah commented
@kaustubhgupta I've pushed the updated code. Kindly check.

2021-03-19 06:25 UTC, kaustubhgupta approved these changes
LGTM 💯

2021-03-19 07:10 UTC, antrikshmisri approved these changes
LGTM

2021-03-19 07:38 UTC, santushtisharma10 approved these changes
@aashishah 💯

2021-03-21 22:45 UTC, avinashkranjan approved these changes
LGTM..🚀

2021-03-21 22:45 UTC, merged