adding heart disease prediction
avinashkranjan/Amazing-Python-Scripts pull request #638
Opened 2021-03-17 18:35 UTC by aaadddiii

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #618 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-19 06:48 UTC, kaustubhgupta requested changes
Minor changes needed:

2021-03-19 06:48 UTC, kaustubhgupta commented on Heart Disease Prediction/README.md
> +# Heart disease prediction
After this heading, all the headings should be at level two (##)

2021-03-19 06:48 UTC, kaustubhgupta commented on Heart Disease Prediction/requirements.txt
> +asgiref @ file:///tmp/build/80754af9/asgiref_1594338739818/work
The requirements file is overpopulated with unnecessary modules. Clear it and make sure to include only those modules which are used in the script

2021-03-19 06:48 UTC, kaustubhgupta commented on Heart Disease Prediction/script.py
> +model = pickle.load(open("./heart_model.pkl", "rb"))
```suggestion
model = pickle.load(open("./Heart Disease Prediction/heart_model.pkl", "rb"))
```

2021-03-20 07:12 UTC, kaustubhgupta requested changes

2021-03-20 07:12 UTC, kaustubhgupta commented on Heart Disease Prediction/README.md
> +#### By [Adithya Kurien Peter]("https://github.com/aaadddiii")
Level 2 (##)

2021-03-20 07:12 UTC, kaustubhgupta commented on Heart Disease Prediction/requirements.txt
> +packaging==20.4
not needed

2021-03-20 07:12 UTC, kaustubhgupta commented on Heart Disease Prediction/requirements.txt
> +numpy==1.18.5
Replace all these with this list:
numpy
pandas
scikit-learn

2021-03-21 03:17 UTC, aaadddiii commented on Heart Disease Prediction/README.md
> +#### By [Adithya Kurien Peter]("https://github.com/aaadddiii")
Iam sorry , Have made the changes

2021-03-21 03:59 UTC, kaustubhgupta approved these changes

2021-03-21 07:49 UTC, antrikshmisri approved these changes

2021-03-21 07:56 UTC, santushtisharma10 approved these changes

2021-03-21 22:45 UTC, avinashkranjan approved these changes

2021-03-21 22:45 UTC, merged