added ImageToSketch folder
avinashkranjan/Amazing-Python-Scripts pull request #645
Opened 2021-03-18 08:07 UTC by vaishnavirshah

# Description

I have added a menu driven script to convert image to sketch. This image can be taken as a path from user or captured through the webcam. 
This script will require opencv, os and datetime modules.

## Fixes #639 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-19 10:44 UTC, kaustubhgupta requested changes
The script works fine, just a few changes, Only Hulk demo is enough. Retain hulk's images files and remove files associated with your's. Other changes:

2021-03-19 10:44 UTC, kaustubhgupta commented on ImageToSketch/README.md
> +- Vaishnavi Shah sketch
Only Hulk demo is enough, you can remove your's and other ahead

2021-03-19 10:44 UTC, kaustubhgupta commented on ImageToSketch/sketchScript.py
> +    parent_dir = f'C:\\Users\\Hp\\Programming\\Python\\sketch\\sketches'
This will be more generic:
```suggestion
    parent_dir = './ImageToSketch/sketches'
```

2021-03-19 10:44 UTC, kaustubhgupta commented on ImageToSketch/README.md
> +#### By [Vaishnavi Shah](https://github.com/vaishnavirshah)
This needs to be level two (##)

2021-03-19 12:53 UTC, vaishnavirshah commented
@kaustubhgupta I will make the changes, I only had one doubt related to git. I

 had trouble with git last time so I just wanted to confirm if I am doing it right.

Do I make the changes directly on GitHub or should I do it locally and then push them on GitHub?
And if I make the changes locally after updating my forked repo and push it, will they be directly be updated here or do I have to make a PR again.

Just to above past mistakes, wanted to clarify first.

2021-03-19 15:03 UTC, kaustubhgupta commented
> @kaustubhgupta I will make the changes, I only had one doubt related to git. I
> 
> had trouble with git last time so I just wanted to confirm if I am doing it right.
> 
> Do I make the changes directly on GitHub or should I do it locally and then push them on GitHub?
> And if I make the changes locally after updating my forked repo and push it, will they be directly be updated here or do I have to make a PR again.
> 
> Just to above past mistakes, wanted to clarify first.

You need to do your changes locally and then push them. Those commits would be reflected in this PR. Also, make sure that you are in the same local repo (imageToSketch)

2021-03-20 07:18 UTC, kaustubhgupta approved these changes
@vaishnavirshah Perfect 💯 💯

2021-03-20 07:26 UTC, santushtisharma10 approved these changes
@vaishnavirshah 💯

2021-03-20 08:29 UTC, antrikshmisri approved these changes
LGTM 👍🏻

2021-03-21 22:44 UTC, avinashkranjan approved these changes
LGTM.....🚀🚀🚀

2021-03-21 22:44 UTC, merged