Alarm clock project
avinashkranjan/Amazing-Python-Scripts pull request #646
Opened 2021-03-18 08:26 UTC by Anupreetadas

# Description

I have added the Alarm clock project along with the GUI using tkinter module.It allows the user to set alarm and each second the alarm updates itself until the time that is set by user.Once the time is reached the alarm rings with the default sound of windows.

## Fixes #600

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/Anupreetadas/Amazing-Python-Scripts/blob/901a4ecd82957fde36caa8b120c4081b07a40818/Alarm-Clock/README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-19 10:52 UTC, kaustubhgupta requested changes
Remove pic1.jpg as it serves no purpose. These are some more changes:

2021-03-19 10:52 UTC, kaustubhgupta commented on Alarm-Clock/README.md
> +
Remove these blank lines at the end

2021-03-19 10:52 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +from tkinter import *
- When time is up, play an alarming tone. 
- Use range function to define Hours, Minutes, and seconds instead of these hardcoded tuples

2021-03-20 07:20 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +from tkinter import *
@Anupreetadas These changes also need to be done

2021-03-21 04:00 UTC, kaustubhgupta commented
@Anupreetadas updates?

2021-03-22 05:02 UTC, kaustubhgupta requested changes
@Anupreetadas Why have you messed up? Along with these changes, do the changes suggested before

2021-03-22 05:02 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +time_format=Label(root, text= "Enter time in 24 hour format!", fg="red",bg="black",font="Arial").place(x=60,y=120)
```suggestion
Label(root, text= "Enter time in 24 hour format!", fg="red",bg="black",font="Arial").place(x=60,y=120)
```

2021-03-22 05:02 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +addTime = Label(root,text = "Hour  Min   Sec",font=60).place(x = 110,y=40)
```suggestion
Label(root,text = "Hour  Min   Sec",font=60).place(x = 110,y=40)
```

2021-03-22 05:02 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +setYourAlarm = Label(root,text = "When to wake you up",fg="blue",relief = "solid",font=("Helevetica",7,"bold")).place(x=0, y=80)
```suggestion
Label(root,text = "When to wake you up",fg="blue",relief = "solid",font=("Helevetica",7,"bold")).place(x=0, y=80)
```

2021-03-22 05:02 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +hourTime= Entry(root,textvariable = hour,bg = "white",width = 15).place(x=110,y=80)
```suggestion
Entry(root,textvariable = hour,bg = "white",width = 15).place(x=110,y=80)
```

2021-03-22 05:02 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +minTime= Entry(root,textvariable = minute,bg = "white",width = 15).place(x=150,y=80)
```suggestion
Entry(root,textvariable = minute,bg = "white",width = 15).place(x=150,y=80)
```

2021-03-22 05:02 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +secTime = Entry(root,textvariable = second,bg = "white",width = 15).place(x=200,y=80)
```suggestion
Entry(root,textvariable = second,bg = "white",width = 15).place(x=200,y=80)
```

2021-03-22 05:21 UTC, Anupreetadas commented
> @Anupreetadas Why have you messed up? Along with these changes, do the changes suggested before

Whenever I try to add the "alarm.wav" file it shows "Lint code base:All jobs failed"
So i tried to do some changes to the code but same problem shows each time I do any change.

2021-03-22 05:22 UTC, kaustubhgupta commented
> > @Anupreetadas Why have you messed up? Along with these changes, do the changes suggested before
> 
> Whenever I try to add the "alarm.wav" file it shows "Lint code base:All jobs failed"
> So i tried to do some changes to the code but same problem shows each time I do any change.

"Lint code base:All jobs failed" it fails not because of audio but the extra changes you made in the code. I have pointed out them above

2021-03-22 15:33 UTC, kaustubhgupta requested changes
Some bugs:
- The path of audio needs to be corrected for which I have suggested the change below
- When the time is up, the sound plays even after clicking on the cross and when the program exits, this error pops up:
![image](https://user-images.githubusercontent.com/43691873/112014956-5fc09300-8b51-11eb-922b-802adf6ac73f.png)

2021-03-22 15:33 UTC, kaustubhgupta commented on Alarm-Clock/README.md
> +
@Anupreetadas this change also needs to be done

2021-03-22 15:33 UTC, kaustubhgupta commented on Alarm-Clock/alarm-clock.py
> +            playsound('alarm.wav')
```suggestion
            playsound('./Alarm-Clock/alarm.wav') 
```

2021-03-24 05:45 UTC, kaustubhgupta commented
@Anupreetadas you didn't make any changes? Final updates for this?

2021-03-24 09:00 UTC, Anupreetadas commented
> @Anupreetadas you didn't make any changes? Final updates for this?

Sorry for the delay.I will push the modified one by today.

2021-03-25 04:41 UTC, kaustubhgupta reviewed
@Anupreetadas Did you tested the script before updating it?
![image](https://user-images.githubusercontent.com/43691873/112419952-55211c00-8d52-11eb-8563-7d63ab2a5def.png)

2021-03-26 05:51 UTC, kaustubhgupta commented
@Anupreetadas this PR has conflicting files and the code hasn't been updated

2021-03-27 04:36 UTC, kaustubhgupta commented
@Anupreetadas I am closing this PR as it has merge conflicts plus a lot of commits are made which are difficult to manage. I would request you to make a new PR for this issue. Make sure to create a new branch and delete this branch. Migrate all the suggested changes in the new PR

2021-03-27 04:36 UTC, closed without merging