Image to speech folder is added
avinashkranjan/Amazing-Python-Scripts pull request #663
Opened 2021-03-19 06:10 UTC by Subhradeep10

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-19 12:03 UTC, kaustubhgupta commented
@Subhradeep10 May I know where is the issue for this PR?

2021-03-20 03:50 UTC, Subhradeep10 commented
@kaustubhgupta The Mentors are reviewing it..

2021-03-20 08:01 UTC, kaustubhgupta commented
@Subhradeep10 I am the mentor of this project and I haven't got any issue from your side

2021-03-21 04:09 UTC, kaustubhgupta commented
@Subhradeep10 ?

2021-03-21 06:53 UTC, Subhradeep10 commented
@kaustubhgupta I did'nt mentioned any issue..I contruibuted my own folder in amazing pything scripts repo

2021-03-21 06:55 UTC, Subhradeep10 commented
@kaustubhgupta Actually I am new to git and github ...So it will take lil bit time to familiarize it....But I think I didn't raised any issue

2021-03-21 07:39 UTC, kaustubhgupta commented
> @kaustubhgupta Actually I am new to git and github ...So it will take lil bit time to familiarize it....But I think I didn't raised any issue

Then raise an issue for this

2021-03-22 05:20 UTC, kaustubhgupta commented
@Subhradeep10 ?

2021-03-22 16:58 UTC, santushtisharma10 requested changes
@Subhradeep10 add a readme file

2021-03-22 17:10 UTC, santushtisharma10 requested changes
@Subhradeep10 also delete main.py file. There is no use of it

2021-03-22 17:10 UTC, santushtisharma10 commented on Image to Speech/image_to_text.py
> +
@Subhradeep10  take the file path as input from user instead of hard coding it

2021-03-23 04:23 UTC, kaustubhgupta requested changes
Delete the output.mp3 file from this repo. Other changes:

2021-03-23 04:23 UTC, kaustubhgupta commented on Image to Speech/image_to_text.py
> +pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
take the input for this also

2021-03-23 04:23 UTC, kaustubhgupta commented on Image to Speech/image_to_text.py
> +os.system("start output.mp3")
After playing this audio, delete the file created (output.mp3). Suggested module: os

2021-03-25 04:44 UTC, kaustubhgupta commented
@Subhradeep10 Have you looked at the suggested changes?

2021-03-26 05:53 UTC, kaustubhgupta commented
@Subhradeep10 Will you fix this PR?

2021-03-27 04:37 UTC, closed without merging

2021-03-27 04:37 UTC, kaustubhgupta commented
PR closed due to no response from participant