Added Eyes Detection
avinashkranjan/Amazing-Python-Scripts pull request #667
Opened 2021-03-19 12:47 UTC by Avishake007

# Description

It will detect your eyes and will count the number of eyes 

## Fixes #629 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.
![eyes(2)](https://user-images.githubusercontent.com/56298861/111782556-27198300-88df-11eb-80c6-aa8ad5a3a51c.PNG)

2021-03-20 07:40 UTC, santushtisharma10 requested changes

2021-03-20 07:40 UTC, santushtisharma10 commented on Eyes Detection/README.md
> +<h1 align="center"> Body Detection</h1>
@Avishake007 change the heading to Eye Detection

2021-03-20 07:40 UTC, santushtisharma10 commented on Eyes Detection/eyes.py
> +
@Avishake007  add `capture.release()`

2021-03-20 07:51 UTC, Avishake007 commented
Sure, I will change it and commit again

2021-03-21 04:13 UTC, kaustubhgupta requested changes
Just one minor change:

2021-03-21 04:13 UTC, kaustubhgupta commented on Eye Detection/eyes.py
> +    eye_cascade=cv2.CascadeClassifier('haarcascade_eye.xml')
```suggestion
    eye_cascade=cv2.CascadeClassifier('./Eye Detection/haarcascade_eye.xml')
```

2021-03-22 05:24 UTC, kaustubhgupta requested changes

2021-03-22 05:24 UTC, kaustubhgupta commented on Eye Detection/eyes.py
> +    eye_cascade=cv2.CascadeClassifier('../Eye Detection/haarcascade_eye.xml')
```suggestion
    eye_cascade=cv2.CascadeClassifier('./Eye Detection/haarcascade_eye.xml')
```

2021-03-22 06:46 UTC, Avishake007 commented
@kaustubhgupta  when I am making **eye_cascade=cv2.CascadeClassifier('./Eye Detection/haarcascade_eye.xml')** change in my code its giving an error 
![eyes(3)](https://user-images.githubusercontent.com/56298861/111950078-cc16a480-8b07-11eb-85ab-2a9681f528f3.PNG)
 but when I am keeping my files and folder structure like this 
![eyes(4)](https://user-images.githubusercontent.com/56298861/111950475-54954500-8b08-11eb-8317-148b800d6670.PNG)
its working. So will I keep the cascade file according to this format

2021-03-22 06:51 UTC, kaustubhgupta commented
> @kaustubhgupta when I am making **eye_cascade=cv2.CascadeClassifier('./Eye Detection/haarcascade_eye.xml')** change in my code its giving an error
> ![eyes(3)](https://user-images.githubusercontent.com/56298861/111950078-cc16a480-8b07-11eb-85ab-2a9681f528f3.PNG)
> but when I am keeping my files and folder structure like this
> ![eyes(4)](https://user-images.githubusercontent.com/56298861/111950475-54954500-8b08-11eb-8317-148b800d6670.PNG)
> its working. So will I keep the cascade file according to this format and then make the necessary changes

As you have the same folder named Eye Detection storing another folder Eye Detection. then according to hierarchy, it is referring to the upper level folder. You can commit my suggestion and it will work everywhere

2021-03-22 11:41 UTC, Avishake007 commented
@kaustubhgupta  Its done Kindly check

2021-03-22 15:35 UTC, kaustubhgupta approved these changes
@Avishake007 💯

2021-03-22 16:41 UTC, santushtisharma10 approved these changes
@Avishake007 💯

2021-03-24 06:00 UTC, kaustubhgupta commented
@antrikshmisri

2021-03-24 06:05 UTC, antrikshmisri approved these changes

2021-03-25 20:24 UTC, avinashkranjan approved these changes

2021-03-25 20:24 UTC, merged