News scrapper
avinashkranjan/Amazing-Python-Scripts pull request #674
Opened 2021-03-19 16:36 UTC by paulamib123

# Description

This Script is used to get top 10 headlines from India Today based on the category entered by the user and stores it in a CSV file.  

## Fixes #495 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-20 08:51 UTC, kaustubhgupta requested changes
The script works perfect, just a minor readme update

2021-03-20 08:51 UTC, kaustubhgupta commented on News_Scrapper/README.md
> +#### By [Paulami Bhattacharya](https://github.com/paulamib123)
Level two (##)

2021-03-20 08:53 UTC, antrikshmisri approved these changes
LGTM 👍🏻

2021-03-20 12:25 UTC, paulamib123 commented on News_Scrapper/README.md
> +#### By [Paulami Bhattacharya](https://github.com/paulamib123)
I made the changes, Please have a look.

2021-03-20 12:26 UTC, santushtisharma10 approved these changes
@paulamib123 💯

2021-03-20 12:48 UTC, kaustubhgupta approved these changes
Perfect, did the same I was expecting 😄👍

2021-03-21 22:42 UTC, avinashkranjan approved these changes
LGTM.....🚀🚀🚀

2021-03-21 22:42 UTC, merged