issue #636  @censor_word_detection
avinashkranjan/Amazing-Python-Scripts pull request #680
Opened 2021-03-20 06:13 UTC by jeelnathani

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-20 09:04 UTC, kaustubhgupta requested changes

2021-03-20 09:04 UTC, kaustubhgupta commented on Censor word detection/README.md
> +      <li>It will print **** if profanity.censor(text) is used.</li>
this never printed?

2021-03-20 09:04 UTC, kaustubhgupta commented on Censor word detection/censor_word_detection.py
> +        '''profanity.censor(data) will print **** '''
this line is not need as it never printed ***

2021-03-20 10:24 UTC, jeelnathani commented
changes are done

On Sat, Mar 20, 2021 at 2:35 PM Kaustubh Gupta ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Censor word detection/README.md
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/680#discussion_r598085662>
> :
>
> > +
> +
> +<h3>Requirements</h3>
> +<ul>
> +  <li>Run the command:
> +    pip install better_profanity</li>
> +</ul>
> +
> +<h3> Approach </h3>
> +<ol>
> +  <li>Import the module profanity from better_profanity</li>
> +  <li>Take user input </li>
> +  <li>Check for the censored data using method profanity.censor() </li>
> +  <li>Print the output on terminal.
> +    <ul>
> +      <li>It will print **** if profanity.censor(text) is used.</li>
>
> this never printed?
> ------------------------------
>
> In Censor word detection/censor_word_detection.py
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/680#discussion_r598085715>
> :
>
> > @@ -0,0 +1,14 @@
> +from better_profanity import profanity
> +
> +def detect(data):
> +    try:
> +        '''profanity.censor(data) will print **** '''
>
> this line is not need as it never printed ***
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/680#pullrequestreview-616896692>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI6BY4SNSKZQ53746N7J62TTERQMPANCNFSM4ZQDHQ2Q>
> .
>

2021-03-20 12:08 UTC, kaustubhgupta commented on Censor word detection/censor_word_detection.py
> +        '''profanity.censor(data) will print **** '''
@jeelnathani this is still left

2021-03-20 12:19 UTC, jeelnathani commented
Done

On Sat, 20 Mar, 2021, 5:38 pm Kaustubh Gupta, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Censor word detection/censor_word_detection.py
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/680#discussion_r598103667>
> :
>
> > @@ -0,0 +1,14 @@
> +from better_profanity import profanity
> +
> +def detect(data):
> +    try:
> +        '''profanity.censor(data) will print **** '''
>
> @jeelnathani <https://github.com/jeelnathani> this is still left
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/680#discussion_r598103667>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI6BY4XEOLHRJGJDEEJVBVDTESF27ANCNFSM4ZQDHQ2Q>
> .
>

2021-03-20 12:47 UTC, kaustubhgupta approved these changes

2021-03-20 13:01 UTC, santushtisharma10 approved these changes
LGTM 💯

2021-03-20 18:05 UTC, antrikshmisri approved these changes
LGTM 👍🏻

2021-03-21 22:41 UTC, avinashkranjan approved these changes
LGTM..🚩

2021-03-21 22:41 UTC, merged