Update face-detect.py
avinashkranjan/Amazing-Python-Scripts pull request #681
Opened 2021-03-20 11:14 UTC by Avishake007

# Description

I have made some updates in the face-detect.py file:
- Counted number of faces visible
- Added press q to quit

## Fixes #668 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-20 12:38 UTC, santushtisharma10 requested changes
@Avishake007 

- add a readme file.
- Add `cv2.destroyAllWindows()` at the end of your code

2021-03-20 13:23 UTC, Avishake007 commented
@santushtisharma10  its done

2021-03-20 18:03 UTC, antrikshmisri requested changes
No need to type cast `a` , you can simply do this

2021-03-20 18:03 UTC, antrikshmisri commented on Face-Detection/face-detect.py
> +        a=str(len(face))
```suggestion
        a=len(face)
```

2021-03-20 18:03 UTC, antrikshmisri commented on Face-Detection/face-detect.py
> +        if int(a)==1:
```suggestion
        if a==1:
```

2021-03-20 18:03 UTC, antrikshmisri commented on Face-Detection/face-detect.py
> +            cv2.putText(img,a+"face detected",(15,350), font, 2,(255,0,0),2,cv2.LINE_AA)
```suggestion
            cv2.putText(img,f"{a}face detected",(15,350), font, 2,(255,0,0),2,cv2.LINE_AA)
```

2021-03-20 18:03 UTC, antrikshmisri commented on Face-Detection/face-detect.py
> +            cv2.putText(img,a+"faces detected",(15,350), font, 2,(255,0,0),2,cv2.LINE_AA)
```suggestion
            cv2.putText(img,f"{a}face detected",(15,350), font, 2,(255,0,0),2,cv2.LINE_AA)
```

2021-03-21 04:28 UTC, kaustubhgupta reviewed
Wait, you don't need to make changes to the current file. Create a folder called v3 and name the script as face_detectv3.py and put the code there. This is because, in another PR #682, he will also do the same thing as v2. Shift the readme and model XML to v3 folder

2021-03-21 04:42 UTC, Avishake007 commented
@kaustubhgupta Will I create  the v3 folder inside the face detection folder or in the main folder?

2021-03-21 05:05 UTC, kaustubhgupta commented
> @kaustubhgupta Will I create the v3 folder inside the face detection folder or in the main folder?

Inside face detection folder

2021-03-21 05:55 UTC, Avishake007 commented
@antrikshmisri  and @kaustubhgupta  I have made the necessary changes. Kindly check

2021-03-22 05:29 UTC, kaustubhgupta requested changes

2021-03-22 05:29 UTC, kaustubhgupta commented on Face-Detection/v3/face_detectv3.py
> +face_cascade = cv2.CascadeClassifier("haarcascade_frontalface.xml")
```suggestion
face_cascade = cv2.CascadeClassifier("./Face-Detection/v3/haarcascade_frontalface.xml")
```

2021-03-22 15:38 UTC, kaustubhgupta approved these changes
@Avishake007 💯

2021-03-22 16:52 UTC, santushtisharma10 approved these changes

2021-03-24 06:01 UTC, kaustubhgupta commented
@antrikshmisri

2021-03-24 06:04 UTC, antrikshmisri approved these changes

2021-03-25 20:22 UTC, avinashkranjan approved these changes

2021-03-25 20:22 UTC, merged