Wikipedia summary GUI
avinashkranjan/Amazing-Python-Scripts pull request #683
Opened 2021-03-20 11:48 UTC by Ayushjain2205

# Description

Script added to generate summary about any topic from wikipedia using a GUI

## Fixes #671 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-21 05:39 UTC, kaustubhgupta requested changes
There is some bug parsing the query from user:

![image](https://user-images.githubusercontent.com/43691873/111895039-dbc5b880-8a35-11eb-8192-4fb2ea5cb5e2.png)

![image](https://user-images.githubusercontent.com/43691873/111895048-eda75b80-8a35-11eb-9497-7a2c2448e4d1.png)

2021-03-21 12:14 UTC, Ayushjain2205 commented
@kaustubhgupta  looking into it...will update you once I figure it out

2021-03-22 15:49 UTC, kaustubhgupta commented
@Ayush7614 did you go the workaround?

2021-03-22 15:50 UTC, kaustubhgupta commented
or shall I help in debugging?

2021-03-22 18:27 UTC, Ayushjain2205 commented
@kaustubhgupta I have made the changes , can you please test it again and let me know if it is fine now

2021-03-23 04:31 UTC, kaustubhgupta requested changes
Yes, the error has been resloved. Now change the requirements.txt as suggested

2021-03-23 04:31 UTC, kaustubhgupta commented on Wikipedia-Summary-GUI/requirements.txt
> +wikipedia
```suggestion
pymediawiki
```

2021-03-23 06:52 UTC, Ayushjain2205 commented
Done, I have updated the requirements file

2021-03-23 14:42 UTC, kaustubhgupta approved these changes
Cool @Ayushjain2205 💯

2021-03-23 16:30 UTC, santushtisharma10 approved these changes
@Ayushjain2205 💯 💯

2021-03-24 12:23 UTC, santushtisharma10 commented
@antrikshmisri

2021-03-24 12:29 UTC, antrikshmisri approved these changes

2021-03-25 20:22 UTC, avinashkranjan approved these changes
LGTM

2021-03-25 20:22 UTC, merged