Crossword solver in Python
avinashkranjan/Amazing-Python-Scripts pull request #684
Opened 2021-03-20 11:49 UTC by aliya-rahmani

# Description
Added a python AI based on constraint satisfaction algorithm that solves crossword puzzles.
## Fixes #(594)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-21 06:01 UTC, kaustubhgupta requested changes

2021-03-21 15:48 UTC, kaustubhgupta requested changes

2021-03-21 15:48 UTC, kaustubhgupta commented on Crossword Solver/generate.py
> +        font = ImageFont.truetype("assets/fonts/OpenSans-Regular.ttf", 80)
There is no folder named assets/fonts/ .

2021-03-22 05:35 UTC, kaustubhgupta requested changes

2021-03-22 05:35 UTC, kaustubhgupta commented on Crossword Solver/generate.py
> +        font = ImageFont.truetype("OpenSans-Regular.ttf", 80)
```suggestion
        font = ImageFont.truetype("./Crossword Solver/OpenSans-Regular.ttf", 80)
```

2021-03-22 06:47 UTC, aliya-rahmani commented
@kaustubhgupta I've applied the requested changes, please review it further.

2021-03-22 06:52 UTC, kaustubhgupta approved these changes

2021-03-25 04:45 UTC, kaustubhgupta commented
@santushtisharma10 @Kushal997-das

2021-03-25 05:56 UTC, santushtisharma10 commented
@aliya-rahmani you have copied your code from [here](https://github.com/PLCoster/cs50ai-week3-crossword)

2021-03-25 08:55 UTC, kaustubhgupta commented
> @aliya-rahmani you have copied your code from [here](https://github.com/PLCoster/cs50ai-week3-crossword)

yes, fully copied. This PR and issue will be closed @aliya-rahmani

2021-03-25 08:55 UTC, closed without merging