LinkedIn Connections Scrapper
avinashkranjan/Amazing-Python-Scripts pull request #698
Opened 2021-03-21 21:06 UTC by XZANATOL

# Description

Added LinkedIn Connections Scrapper.

### Notes
1) I've added script output files of my LinkedIn small connections list [here](https://drive.google.com/file/d/1sS9Dhw6JYFJn8Ui91p5jSD7_p7N7ArBi/view?usp=sharing). (Skills column not Included.)
2) For the skills scrapping, I've extracted the function responsible for this work and tried it alone on my LinkedIn profile. Results can be viewed [here](https://drive.google.com/file/d/1VD6z5eK3gA-hx6M3ZLteRls8IN1kFFbG/view?usp=sharing)

## Fixes #56 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-22 08:52 UTC, kaustubhgupta requested changes
Just minor corrections, else the script works great

2021-03-22 08:52 UTC, kaustubhgupta commented on Linkedin_Connections_Scrapper/ReadMe.md
> +# Usage
Explain the differences between basic and scrapping usage. I mean a one-liner for the expected output

2021-03-22 08:52 UTC, kaustubhgupta commented on Linkedin_Connections_Scrapper/ReadMe.md
> +Reviewed by [Kaustubh Gupta](https://github.com/kaustubhgupta).
This PR will be reviewed by other mentors too so it would be unfair for them. You can remove this line

2021-03-22 08:52 UTC, kaustubhgupta commented on Linkedin_Connections_Scrapper/script.py
> +# Mentored by avinashkranjan & kaustubhgupta / GSSOC'21
As mentioned earlier :-)

2021-03-22 13:09 UTC, XZANATOL commented
@kaustubhgupta Done.

2021-03-22 15:57 UTC, kaustubhgupta approved these changes
@XZANATOL great job again 💯 😃

2021-03-22 19:07 UTC, antrikshmisri requested changes

2021-03-22 19:07 UTC, antrikshmisri commented on Linkedin_Connections_Scrapper/script.py
> +def login(email, password):
Please add some logic to verify if user was logged in or not. You can do that by either looking for the error message or by checking the page title by using `driver.title`

2021-03-22 21:53 UTC, XZANATOL commented
@antrikshmisri Done.

2021-03-23 09:51 UTC, antrikshmisri approved these changes
All good now 💯

2021-03-25 05:10 UTC, kaustubhgupta commented
@santushtisharma10

2021-03-25 06:56 UTC, santushtisharma10 approved these changes

2021-03-25 20:21 UTC, avinashkranjan approved these changes
LGTM..Great job @XZANATOL

2021-03-25 20:21 UTC, merged