Lachenlama
avinashkranjan/Amazing-Python-Scripts pull request #705
Opened 2021-03-22 10:27 UTC by lachenlama

# Description

Tetris : The Game made with pygame. Easy to install and play.

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

## Checklist:

- [x ] My code follows the style guidelines(Clean Code) of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [x ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-22 10:34 UTC, lachenlama commented
#632  Issue PR

2021-03-22 16:20 UTC, kaustubhgupta requested changes
Code works fine, just some minor changes

2021-03-22 16:20 UTC, kaustubhgupta commented on Tetris/readme.md
> +* ![Ingame image1](https://drive.google.com/file/d/1PlqBkTrg_UqKGECBgChZ7UZfrdCKmaYy/view?usp=sharing)
images note rendered

2021-03-22 16:20 UTC, kaustubhgupta commented on Tetris/requirements.txt
> +Package    Version
just mention the package names with version like: pygame==20.2.3 without top heading and next dashed lines

2021-03-22 18:50 UTC, antrikshmisri approved these changes

2021-03-22 18:50 UTC, antrikshmisri commented on Tetris/readme.md
> +# Tetris : The Game
Add all the dependencies

2021-03-23 09:52 UTC, antrikshmisri requested changes
Add the dependencies in README.md

2021-03-25 05:11 UTC, kaustubhgupta commented
@lachenlama Have you looked at the changes suggested?

2021-03-25 13:26 UTC, lachenlama commented
Will look into it now sorry, haven't been very active recently @kaustubhgupta

2021-03-25 16:08 UTC, lachenlama commented
Please, do check again. If there is any issue do tell me. I am very new in this tbh but i willing to grind @kaustubhgupta

2021-03-26 06:09 UTC, kaustubhgupta reviewed
Plagiarism Strike 1
https://levelup.gitconnected.com/writing-tetris-in-python-2a16bddb5318

2021-03-26 06:11 UTC, closed without merging