Plagiarism-Checker
avinashkranjan/Amazing-Python-Scripts pull request #707
Opened 2021-03-22 14:32 UTC by Anupreetadas

# Description

I have added the plagiarism checker project which helps user to check similarity between two text files.It computes similarity when the textual raw data is transformed into vectors and then to arrays of numbers and then from that we can compute the the similarity between them.

## Fixes #655

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/Anupreetadas/Amazing-Python-Scripts/blob/branch_name2/Plagiarism-Checker/README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-22 16:21 UTC, kaustubhgupta requested changes
Alarm clock files are pushed here?

2021-03-22 16:31 UTC, Anupreetadas commented
> Alarm clock files are pushed here?

I am so sorry ,It happened because I made another branch to push this project.It is fixed now . Sorry for the inconvinience caused.It wont happen again.

2021-03-23 04:45 UTC, kaustubhgupta approved these changes

2021-03-23 04:45 UTC, kaustubhgupta commented on Plagiarism-Checker/.vscode/settings.json
> +{
this file is not needed, you can delete it

2021-03-23 06:01 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-23 09:53 UTC, antrikshmisri approved these changes
LGTM 👍🏻

2021-03-23 16:32 UTC, santushtisharma10 approved these changes

2021-03-25 01:16 UTC, kaustubhgupta commented
@Anupreetadas Umm, why you messed up this branch? Why there are alarm clock files in this branch?

2021-03-25 20:20 UTC, merged