Adding the python script for image editor and the readme.md file
avinashkranjan/Amazing-Python-Scripts pull request #716
Opened 2021-03-23 06:45 UTC by asmita20aggarwal

# Description

This is my first pull request. I have added the python script for the image editor along with the readme.md file.

## Fixes #(#647)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ✔] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ✔] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [✔ ] Documentation Update

## Checklist:

- [ ✔] My code follows the style guidelines(Clean Code) of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas
- [✔ ] I have created a helpful and easy to understand `README.md`
- [ ✔] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ✔] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-23 15:07 UTC, kaustubhgupta requested changes
Minor changes needed:

2021-03-23 15:07 UTC, kaustubhgupta commented on Image editor python script/Image_editing_script.py
> +    preview_choice = input("Type 1 for yes and 2 for no : ")
Be consistent with upper and lower case:
```suggestion
    preview_choice = input("Type 1 for YES and 2 for NO : ")
```

2021-03-23 17:01 UTC, asmita20aggarwal commented
@kaustubhgupta Sir, I have made the suggested changes.

2021-03-24 06:05 UTC, kaustubhgupta approved these changes

2021-03-25 05:22 UTC, kaustubhgupta commented
@Kushal997-das

2021-03-25 09:53 UTC, santushtisharma10 approved these changes
Nice @asmita20aggarwal 💯💯

2021-03-25 11:21 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-25 12:02 UTC, asmita20aggarwal commented
Thankyou :)

2021-03-25 20:18 UTC, merged