Added your meeting buddy
avinashkranjan/Amazing-Python-Scripts pull request #728
Opened 2021-03-24 11:20 UTC by Yuvraj-kadale

# Description
Added "Your meeting buddy", This buddy will help you join the meetings in your absence at a scheduled time saved in your google calendar. 

## Fixes #702 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-24 12:57 UTC, santushtisharma10 requested changes

2021-03-24 12:57 UTC, santushtisharma10 commented on Your Meeting Buddy/Gmeet_buddy.py
> +
@Yuvraj-kadale instead of harcoding the credential, take the input from the user

2021-03-25 10:29 UTC, santushtisharma10 commented
@kaustubhgupta i am facing error while running the script on my local machine. Please confirm if the script is working or not.

2021-03-25 10:36 UTC, Yuvraj-kadale commented
> @kaustubhgupta i am facing error while running the script on my local machine. Please confirm if the script is working or not.

Could you please let me know the error You are getting?

2021-03-25 10:51 UTC, Yuvraj-kadale commented
@santushtisharma10 could you please sure that you have downloaded chrome driver, and have defined the correct path in the code. I have tried running the script in my local machine. The working can be viewed [here](https://youtu.be/auJaJZ_h0gE)

2021-03-25 11:31 UTC, santushtisharma10 commented
> @santushtisharma10 could you please sure that you have downloaded chrome driver, and have defined the correct path in the code. I have tried running the script in my local machine. The working can be viewed [here](https://youtu.be/auJaJZ_h0gE)

Yes i have downloaded it and the path was also correct. And i saw the working of your script ,but still getting an error on my local system, so will confirm it with @kaustubhgupta . If he is able to run it successfully on his local system, then I will approve the PR.

2021-03-26 06:53 UTC, kaustubhgupta requested changes
@santushtisharma10 The script works, @Yuvraj-kadale Here are some suggested changes:

2021-03-26 06:53 UTC, kaustubhgupta commented on Your Meeting Buddy/Gmeet_buddy.py
> +browser =webdriver.Chrome(chrome_options=opt,executable_path="C:\\Users\\path where your chrome driver is saved")   #Enter the path of your chrome driver
take input for the web driver path from user

2021-03-26 06:53 UTC, kaustubhgupta commented on Your Meeting Buddy/Readme.md
> +### Quick links to the driver:
```suggestion
## Quick links to the driver:
```

2021-03-26 06:53 UTC, kaustubhgupta commented on Your Meeting Buddy/Readme.md
> +### How to wake my buddy?
```suggestion
## How to wake my buddy?
```

2021-03-27 04:46 UTC, kaustubhgupta approved these changes

2021-03-27 04:47 UTC, kaustubhgupta commented
@Kushal997-das

2021-03-27 04:52 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-27 05:22 UTC, santushtisharma10 approved these changes

2021-03-27 16:56 UTC, avinashkranjan approved these changes
LGTM..Great Job @Yuvraj-kadale

2021-03-27 16:56 UTC, merged