Watermark Maker(For Images)
avinashkranjan/Amazing-Python-Scripts pull request #758
Opened 2021-03-27 08:49 UTC by aishwaryachand

# Description

- Apart from the previous PR #628  Added user defined position option and textwrap  of multiple lines 

## Fixes #546 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [x] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-27 12:43 UTC, santushtisharma10 approved these changes
@aishwaryachand 💯💯

2021-03-27 12:43 UTC, santushtisharma10 commented
@Kushal997-das

2021-03-28 04:27 UTC, kaustubhgupta requested changes

2021-03-28 04:27 UTC, kaustubhgupta commented on Watermark Maker(On Image)/README.md
> +
Remove this longgg extra space

2021-03-28 04:27 UTC, kaustubhgupta commented on Watermark Maker(On Image)/Watermarker(Image).py
> +print("Where you want to input the text . Pls enter\n 1 - Top Left \n 2 - Top Right \n 3 - Bottom Left \n 4 - Bottom Right \n 5 - Center")
Here, the choice is ambiguous. One is not sure whether to input is the number associated with position or the position itself. Add a print statement to clarify this

2021-03-28 04:27 UTC, kaustubhgupta commented on Watermark Maker(On Image)/Watermarker(Image).py
> +text = input('Enter the text for the  watermark:' )
```suggestion
text = input('Enter the text for the  watermark: ' )

```

2021-03-28 06:57 UTC, antrikshmisri commented
@kaustubhgupta Almost all scripts don't follow PEP8 requirements. I think deploying a autopep8 bot on the repo would save us a ton of time. [Here's](https://github.com/OrkoHunter/pep8speaks) the link to it

2021-03-28 07:37 UTC, kaustubhgupta commented
> @kaustubhgupta Almost all scripts don't follow PEP8 requirements. I think deploying a autopep8 bot on the repo would save us a ton of time. [Here's](https://github.com/OrkoHunter/pep8speaks) the link to it

Yes, this is a good idea. @avinashkranjan can you include this in workflows or should we make an issue for the participants to contribute?

2021-03-28 10:45 UTC, aishwaryachand commented
Made the changes as requested. Kindly review .

2021-03-29 01:38 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-30 04:48 UTC, kaustubhgupta requested changes

2021-03-30 04:48 UTC, kaustubhgupta commented on Watermark Maker(On Image)/README.md
> +
@aishwaryachand This is still not removed

2021-03-30 05:29 UTC, kaustubhgupta approved these changes

2021-03-30 05:29 UTC, kaustubhgupta commented
@antrikshmisri

2021-03-30 05:57 UTC, antrikshmisri approved these changes

2021-03-30 18:15 UTC, avinashkranjan approved these changes
LGTM..💯

2021-03-30 18:15 UTC, merged