Added Google Meet Scheduler
avinashkranjan/Amazing-Python-Scripts pull request #759
Opened 2021-03-27 09:20 UTC by Tarun-Kamboj

# Description

Added a Python Script to schedule a google meet, send invitation to the respective emails and set an event for the meet in the calendar too. The script will take email ids of the guests and time as input and create a google meet for these email ids at the specified time. These email ids will also receive an invite in the gmail inbox and an event will also be created in the calendar of these email ids for the meeting.

## Fixes #724

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-28 04:38 UTC, kaustubhgupta requested changes

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/.gitignore
> +credentials.json
this file is not needed, delete it

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/README.md
> +<p align="center"><img height="250px" src="images/3.png"></p>
image not rendered in markdown output

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/README.md
> +#### Step 2. Modify this part of the code as per your needs.
you need to take these as inputs from the user, remove this step and delete the corresponding image

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/README.md
> +#### Step 4. Now if you run the script for the first time then you'll be requested to grant some permissions.
None of the images here got rendered in the output. It's due to messed up paths of the image

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/script.py
> +topic = 'Topic of the meeting' # replace with suitable topic
take input from user

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/script.py
> +time = {
take input from user

2021-03-28 04:38 UTC, kaustubhgupta commented on Google-Meet-Scheduler/script.py
> +guests = {
take input from user

2021-03-28 06:09 UTC, Tarun-Kamboj commented
@kaustubhgupta check for the requested changes now.

2021-03-30 04:52 UTC, kaustubhgupta approved these changes

2021-03-30 04:53 UTC, kaustubhgupta commented
@Kushal997-das

2021-03-30 07:28 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-31 15:05 UTC, antrikshmisri approved these changes

2021-04-01 05:51 UTC, kaustubhgupta commented
@santushtisharma10

2021-04-01 05:58 UTC, santushtisharma10 approved these changes

2021-04-02 16:45 UTC, avinashkranjan approved these changes

2021-04-02 16:46 UTC, merged