Simple Python IDE using Tkinter
avinashkranjan/Amazing-Python-Scripts pull request #773
Opened 2021-03-29 08:13 UTC by Priyadarshan2000

# Description

I have made a Simple Python IDE using the Tkinter module in Python. This refers to issue number #764 which was assigned to me. No dependencies are required for the change.

## Fixes #764

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-30 05:21 UTC, kaustubhgupta requested changes
Code is working. Just minor changes in readme:

2021-03-30 05:21 UTC, kaustubhgupta commented on Simple Python IDE using Tkinter/README.md
> +# Setup instructions
level two (##)

2021-03-30 05:21 UTC, kaustubhgupta commented on Simple Python IDE using Tkinter/README.md
> +### Requirements:
```suggestion
## Requirements:
```

2021-03-30 05:21 UTC, kaustubhgupta commented on Simple Python IDE using Tkinter/README.md
> +# Output
level two (##)

2021-03-30 05:21 UTC, kaustubhgupta commented on Simple Python IDE using Tkinter/README.md
> +# Demo
give space before this line and level two (##)

2021-03-30 05:21 UTC, kaustubhgupta commented on Simple Python IDE using Tkinter/README.md
> +# Author(s)
level two (##)

2021-03-30 05:59 UTC, Priyadarshan2000 commented
@kaustubhgupta sir what change in the readme file.

2021-03-30 06:19 UTC, Priyadarshan2000 commented
@kaustubhgupta sir I change my Readme file. please check this.

2021-03-31 04:38 UTC, kaustubhgupta approved these changes

2021-03-31 05:46 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-31 06:27 UTC, santushtisharma10 approved these changes
@Priyadarshan2000 💯💯

2021-03-31 15:00 UTC, antrikshmisri approved these changes
LGTM

2021-03-31 20:36 UTC, avinashkranjan approved these changes
LGTM..Great Job @Priyadarshan2000

2021-03-31 20:37 UTC, merged

2021-03-31 20:50 UTC, Priyadarshan2000 commented
Thanks @avinashkranjan sir

2021-03-31 20:52 UTC, avinashkranjan commented
> Thanks @avinashkranjan sir 😊😊

Keep up the good work..😄