Unzip file
avinashkranjan/Amazing-Python-Scripts pull request #775
Opened 2021-03-29 14:53 UTC by Amit366

# Description

Zipped files are converted to unzipped files

## Fixes #651 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

Yes

2021-03-29 14:58 UTC, Amit366 commented
![Screenshot (133)_LI](https://user-images.githubusercontent.com/60662775/112856376-5b562600-90cd-11eb-8dec-79c438707fdc.jpg)

2021-03-29 15:02 UTC, Amit366 commented
![Screenshot (134)](https://user-images.githubusercontent.com/60662775/112856853-dae3f500-90cd-11eb-82d1-92eee48da369.png)

@kaustubhgupta this is the working model

2021-03-30 05:28 UTC, kaustubhgupta requested changes
Code is working. Readme update:

2021-03-30 05:28 UTC, kaustubhgupta commented on Unzip file/Readme.md
> +- First upload the stocks dataset
The description is from previous PRs. Fix this

2021-03-30 05:39 UTC, Amit366 commented
@kaustubhgupta fixed

2021-03-31 04:39 UTC, kaustubhgupta approved these changes

2021-03-31 05:46 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-31 14:59 UTC, antrikshmisri approved these changes

2021-03-31 18:17 UTC, santushtisharma10 approved these changes

2021-03-31 20:37 UTC, avinashkranjan approved these changes

2021-03-31 20:37 UTC, avinashkranjan commented
@Amit366 Resolve the conflict

2021-04-02 16:44 UTC, avinashkranjan approved these changes

2021-04-02 16:44 UTC, merged