Codes on turtle graphics
avinashkranjan/Amazing-Python-Scripts pull request #776
Opened 2021-03-29 15:38 UTC by ricsin23

# Description

I have written two codes on Turtle Graphics which use the turtle Library of Python. This will solve issue  #744. No dependencies are required for this change.

## Fixes #(744)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x]  Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-30 05:38 UTC, kaustubhgupta requested changes
The code is working, just some readme changes:

2021-03-30 05:38 UTC, kaustubhgupta commented on Codes on Turtle Graphics/README.md
> +### Requirements
```suggestion
## Requirements
```

2021-03-30 05:38 UTC, kaustubhgupta commented on Codes on Turtle Graphics/README.md
> +#### 1. Python Environment:
```suggestion
### 1. Python Environment:
```

2021-03-30 05:38 UTC, kaustubhgupta commented on Codes on Turtle Graphics/README.md
> +#### 2. Python Version:
```suggestion
### 2. Python Version:
```

2021-03-30 05:38 UTC, kaustubhgupta commented on Codes on Turtle Graphics/README.md
> +### 1. Animated Robot
```suggestion
## 1. Animated Robot
```

2021-03-30 05:38 UTC, kaustubhgupta commented on Codes on Turtle Graphics/README.md
> +### 2. Kaleido Spiral
```suggestion
## 2. Kaleido Spiral
```

2021-03-30 05:38 UTC, kaustubhgupta commented on Codes on Turtle Graphics/README.md
> +<img src="Kaleido-spiral.png" width="350" height="250">
Images not rendered: 

![image](https://user-images.githubusercontent.com/43691873/112938941-410d5e00-9148-11eb-945b-4eeadd57addf.png)

2021-03-30 05:39 UTC, kaustubhgupta commented
@antrikshmisri again, turtle is not supported

2021-03-31 04:41 UTC, kaustubhgupta approved these changes

2021-03-31 05:45 UTC, Kushal997-das approved these changes
LGTM 💯

2021-03-31 14:43 UTC, antrikshmisri commented
> @antrikshmisri again, turtle is not supported

Yup, did you get any response from the PA?

2021-03-31 14:43 UTC, antrikshmisri approved these changes

2021-04-01 06:17 UTC, santushtisharma10 approved these changes

2021-04-02 16:46 UTC, avinashkranjan approved these changes
LGTM..

2021-04-02 16:46 UTC, merged