Issue 778
avinashkranjan/Amazing-Python-Scripts pull request #782
Opened 2021-03-30 12:59 UTC by Shubhrima

# Description

Added a game, in which the player has to guess the name of the countries on the world map. With every correct guess the player earns a point.

## Fixes #(issue_no)

778

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ x] My code follows the style guidelines(Clean Code) of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have created a helpful and easy to understand `README.md`
- [x ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x ] My changes generate no new warnings
- [ x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-03-31 04:44 UTC, kaustubhgupta requested changes
Have a look at the error logs and fix these issues: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/782/checks?check_run_id=2227796735

2021-04-01 02:12 UTC, Shubhrima commented
@kaustubhgupta  I am unable to understand the errors. Could you please help me out!

2021-04-02 01:02 UTC, Shubhrima commented
@kaustubhgupta I am unable to understand the errors. Could you please help me out! Also, I have used the turtle module here.

2021-04-02 05:50 UTC, kaustubhgupta requested changes
@Shubhrima Your game works. Just do these modifications:

2021-04-02 05:50 UTC, kaustubhgupta commented on Guess the Countries/README.md
> +Package/Script Name
Remove this line

2021-04-02 05:50 UTC, kaustubhgupta commented on Guess the Countries/README.md
> +Output
```suggestion
# Output
```

2021-04-02 05:50 UTC, kaustubhgupta commented on Guess the Countries/README.md
> +<img src='blank.png' width='350'>
Images not rendered:

![image](https://user-images.githubusercontent.com/43691873/113384956-c5f4b380-93a4-11eb-8a23-3e4b79f94553.png)

2021-04-02 05:50 UTC, kaustubhgupta commented on Guess the Countries/README.md
> +
Remove these blank lines

2021-04-02 05:50 UTC, kaustubhgupta commented on Guess the Countries/main.py
> +image='world_map.gif'
```suggestion
image='./Guess the Countries/world_map.gif'
```

2021-04-02 05:50 UTC, kaustubhgupta commented on Guess the Countries/main.py
> +data=pandas.read_csv("country_names.csv")
```suggestion
data=pandas.read_csv("./Guess the Countries/country_names.csv")
```

2021-04-02 12:20 UTC, Shubhrima commented
I made the necessary changes, @kaustubhgupta kindly review this.

2021-04-03 05:26 UTC, kaustubhgupta requested changes

2021-04-03 05:26 UTC, kaustubhgupta commented on Guess the Countries/README.md
> +<img src="blank.png" width="350"/>
```suggestion
![blank](blank.png)
```

2021-04-03 05:26 UTC, kaustubhgupta commented on Guess the Countries/README.md
> +<img src="guessed_countries.png" width="350"/>
```suggestion

![guessed](guessed_countries.png)
```

2021-04-03 05:26 UTC, kaustubhgupta commented on Guess the Countries/main.py
> +image='world_map.gif'
This  suggestion is left

2021-04-03 05:26 UTC, kaustubhgupta commented on Guess the Countries/main.py
> +data=pandas.read_csv("country_names.csv")
This suggestion is left

2021-04-03 12:48 UTC, Shubhrima commented
I made the necessary changes, @kaustubhgupta kindly review this once again.

2021-04-04 10:47 UTC, santushtisharma10 approved these changes
Nice @Shubhrima 💯

2021-04-04 10:48 UTC, santushtisharma10 commented
@Kushal997-das

2021-04-05 14:53 UTC, santushtisharma10 commented
@antrikshmisri @Kushal997-das

2021-04-06 06:38 UTC, kaustubhgupta approved these changes

2021-04-06 07:40 UTC, antrikshmisri approved these changes

2021-04-10 16:40 UTC, avinashkranjan approved these changes

2021-04-10 16:40 UTC, merged