Minesweeper Script
avinashkranjan/Amazing-Python-Scripts pull request #792
Opened 2021-03-31 17:21 UTC by Ratnesh4193

# Description

Added script for MINESWEEPER game #738 

![Capture](https://user-images.githubusercontent.com/57043581/113184732-2f74a500-9273-11eb-8868-61119da9453b.JPG)

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

  Yes

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

@kaustubhgupta plz review

2021-04-01 16:30 UTC, santushtisharma10 requested changes
@Ratnesh4193 code is working fine, but add a few features like when the game is over, add an option to restart the game and exit the game

2021-04-01 17:33 UTC, Ratnesh4193 commented
added restart game feature plz review @santushtisharma10

2021-04-03 09:21 UTC, Ratnesh4193 commented
@kaustubhgupta plz review

2021-04-03 09:41 UTC, santushtisharma10 requested changes
@Ratnesh4193 when the game restarts, make sure that the score is zero instead of adding the previous score.

2021-04-03 11:00 UTC, kaustubhgupta commented
> @kaustubhgupta plz review

Let @santushtisharma10 review it first, after that I will review

2021-04-06 06:41 UTC, kaustubhgupta commented
@Ratnesh4193 updates on this?

2021-04-07 10:18 UTC, Ratnesh4193 commented
I have fixed the bug. Now plz review @santushtisharma10 @kaustubhgupta

2021-04-08 04:37 UTC, kaustubhgupta requested changes

2021-04-08 04:37 UTC, kaustubhgupta commented on MineSweeper/readme.md
> +$--- tkinter
```suggestion
## Modules Used
- tkinter
```

2021-04-08 04:37 UTC, kaustubhgupta commented on MineSweeper/readme.md
> +$--- random (for randomness in game)
```suggestion
-  random (for randomness in game)
```

2021-04-08 05:17 UTC, santushtisharma10 commented
@Ratnesh4193 intitialize the score to zero when the game restart

2021-04-08 05:42 UTC, Ratnesh4193 commented
> @Ratnesh4193 initialize the score to zero when the game restart

Done

2021-04-09 05:29 UTC, santushtisharma10 approved these changes
@Ratnesh4193  💯

2021-04-09 05:31 UTC, santushtisharma10 commented
@Kushal997-das

2021-04-09 07:47 UTC, antrikshmisri approved these changes

2021-04-10 03:41 UTC, kaustubhgupta approved these changes
@Ratnesh4193 💯

2021-04-10 16:41 UTC, avinashkranjan approved these changes
LGTM..💯

2021-04-10 16:41 UTC, merged