Typing Speed test file added
avinashkranjan/Amazing-Python-Scripts pull request #795
Opened 2021-04-01 07:09 UTC by dhriti987

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #720 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-02 06:07 UTC, kaustubhgupta requested changes

2021-04-02 06:07 UTC, kaustubhgupta commented on Typing-Speed-Test/speed_test.py
> +    with open("sentences.txt","r") as f:
```suggestion
    with open("./Typing-Speed-Test/sentences.txt","r") as f:
```

2021-04-02 07:03 UTC, dhriti987 commented
@kaustubhgupta  Done

2021-04-03 03:36 UTC, kaustubhgupta approved these changes

2021-04-03 09:50 UTC, santushtisharma10 approved these changes
Nice @dhriti987 💯

2021-04-04 10:21 UTC, santushtisharma10 commented
@antrikshmisri

2021-04-05 11:39 UTC, santushtisharma10 commented
@Kushal997-das

2021-04-05 11:57 UTC, antrikshmisri approved these changes

2021-04-05 12:34 UTC, avinashkranjan approved these changes
LGTM

2021-04-05 12:34 UTC, merged