Terminal Hangman
avinashkranjan/Amazing-Python-Scripts pull request #796
Opened 2021-04-01 07:36 UTC by Yuvraj-kadale

# Description

Added Terminal Hangman

## Fixes #793 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-02 06:12 UTC, kaustubhgupta requested changes

2021-04-02 06:12 UTC, kaustubhgupta commented on Terminal Hangman/Readme.md
> +#### Easy to begin with, just run the code and terminal says it all.
Remove this line

2021-04-02 06:12 UTC, kaustubhgupta commented on Terminal Hangman/T_hangman.py
> +    word = random.choice(["python",
Store these words in a text file and load from it

2021-04-02 06:12 UTC, kaustubhgupta commented on Terminal Hangman/T_hangman.py
> +    validLetters = 'abcdefghijklmnopqrstuvwxyz'              # All the characters defined in the word list
Using the "string" module to get the alphabets rather than hardcoding them.

2021-04-03 03:38 UTC, kaustubhgupta requested changes

2021-04-03 03:38 UTC, kaustubhgupta commented on Terminal Hangman/T_hangman.py
> +    with open("data.txt", "r") as file:
```suggestion
    with open("./Terminal Hangman/data.txt", "r") as file:
```

2021-04-03 04:54 UTC, Yuvraj-kadale commented
@kaustubhgupta btw both .txt and .py files are in same folder .. and the code was working.

2021-04-04 10:19 UTC, santushtisharma10 approved these changes
@Yuvraj-kadale 💯

2021-04-04 10:20 UTC, santushtisharma10 commented
@Kushal997-das

2021-04-05 14:56 UTC, santushtisharma10 commented
@antrikshmisri @Kushal997-das

2021-04-06 06:42 UTC, kaustubhgupta approved these changes

2021-04-06 07:39 UTC, antrikshmisri approved these changes

2021-04-10 16:42 UTC, avinashkranjan approved these changes
LGTM

2021-04-10 16:42 UTC, merged