Dev.to scraper
avinashkranjan/Amazing-Python-Scripts pull request #802
Opened 2021-04-02 00:21 UTC by Ayushjain2205

# Description

Script to scrape articles from dev.to as per user's choice and save them as pdf

## Fixes #755 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-02 06:27 UTC, kaustubhgupta requested changes

2021-04-02 06:27 UTC, kaustubhgupta commented on Dev.to Scraper/scraper.py
> +driver = webdriver.Chrome('C:\Webdrivers\chromedriver')
Take the chrome driver path input from user

2021-04-02 06:27 UTC, kaustubhgupta commented on Dev.to Scraper/README.md
> +Once the installation is complete, you need to add the webdriver in the path in the following line:
Remove these lines (11 - 14) as input will be taken for this

2021-04-03 05:15 UTC, kaustubhgupta approved these changes
@Ayushjain2205 Good job 💯 💯

2021-04-04 12:00 UTC, Kushal997-das approved these changes
LGTM 💯

2021-04-05 11:43 UTC, santushtisharma10 approved these changes

2021-04-05 11:43 UTC, santushtisharma10 commented
@antrikshmisri

2021-04-05 11:56 UTC, antrikshmisri approved these changes

2021-04-05 12:35 UTC, avinashkranjan approved these changes
LGTM..

2021-04-05 12:35 UTC, merged