Health log book
avinashkranjan/Amazing-Python-Scripts pull request #830
Opened 2021-04-05 07:24 UTC by anuragmukherjee2001

# Description
The script will contain the daily records of food and workouts of a person. The user will only enter the name of the foods, it will be stored in a text file with corresponding date and time. Similarly, the user will enter the types of workout at their workout time. The workouts will be stored in a text file with date and time. The user can also retrieve the data whenever they want to see.

## Modules Used:-
1) datetime

## Fixes #823 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-06 07:15 UTC, kaustubhgupta requested changes
Create a GUI application for this. The current code is not up to the mark for level 2. Also, instead of text files, use mysqlite to store details. If you don't have any experience for that then we need to decrease the level. 

Thoughts? @antrikshmisri @santushtisharma10

2021-04-06 07:15 UTC, kaustubhgupta commented on Health_Log_Book/README.md
> +<img src = "https://user-images.githubusercontent.com/62845847/113548479-3998f980-960d-11eb-806b-4321cec05a98.png" width = "400" height = "300">
This is not the complete image of the script and therefore you can remove this image. Remove this section heading too.

2021-04-06 07:15 UTC, kaustubhgupta commented on Health_Log_Book/main.py
> +# It is a health management system
Remove these 4 line comment

2021-04-06 07:15 UTC, kaustubhgupta commented on Health_Log_Book/README.md
> +### Images of the script:-
As this is not the complete script screenshot, you can remove this image. Remove the section heading too

2021-04-06 07:15 UTC, kaustubhgupta commented on Health_Log_Book/main.py
> +# It is a health management system
Remove these 4 lines and unnecessary comments from the program

2021-04-06 07:36 UTC, antrikshmisri commented
> Create a GUI application for this. The current code is not up to the mark for level 2. Also, instead of text files, use mysqlite to store details. If you don't have any experience for that then we need to decrease the level.
> 
> Thoughts? @antrikshmisri @santushtisharma10

Agreed.

2021-04-06 08:53 UTC, anuragmukherjee2001 commented
Ok sir, I will try to do all the suggested changes. As lots of changes are suggested, so it may take some time. And 1 question sir, can I use SQLite??
@antrikshmisri @santushtisharma10 @kaustubhgupta

2021-04-06 08:54 UTC, santushtisharma10 commented
> Ok sir, I will try to do all the suggested changes. As lots of changes are suggested, so it may take some time. And 1 question sir, can I use SQLite??
> @antrikshmisri @santushtisharma10 @kaustubhgupta

Yes

2021-04-08 04:51 UTC, kaustubhgupta commented
@anuragmukherjee2001 updates on this?

2021-04-08 06:54 UTC, anuragmukherjee2001 commented
> @anuragmukherjee2001 updates on this?

Yes sir, I am making the suggested changes. I will push the changes within tomorrow.

2021-04-09 07:27 UTC, anuragmukherjee2001 commented
I updated the code. Please check it sir.

2021-04-09 12:22 UTC, kaustubhgupta requested changes
If I click on show exercise/food log without entering any information, an exception is raised:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "d:/Projects/Amazing-Python-Scripts/Health_Log_Book/main.py", line 54, in show_food
    cor.execute('''SELECT * from food''')
sqlite3.OperationalError: no such table: food
``` 
Handle this case by giving popup that "No information available"

Also, on clicking show log, the information is printed in the terminal. Display that information in the application GUI only. Create a text area called results to show them

2021-04-10 15:09 UTC, anuragmukherjee2001 commented
Ok sir, trying to correct the mistakes

2021-04-12 05:45 UTC, kaustubhgupta commented
@anuragmukherjee2001 updates?

2021-04-12 15:02 UTC, anuragmukherjee2001 commented
> @anuragmukherjee2001 updates?

I corrected the case which was giving an error. I am working on the feature of showing the information on GUI.

2021-04-14 07:59 UTC, anuragmukherjee2001 commented
I have made all the changes which were suggested. Please Check the PR.

2021-04-15 02:49 UTC, kaustubhgupta approved these changes

2021-04-15 06:54 UTC, antrikshmisri approved these changes

2021-04-16 05:47 UTC, santushtisharma10 approved these changes

2021-04-19 07:25 UTC, avinashkranjan approved these changes
LGTM

2021-04-19 07:25 UTC, merged