Added starter script for scraping n problems according to varying dif…
avinashkranjan/Amazing-Python-Scripts pull request #833
Opened 2021-04-05 16:54 UTC by AshuKV

…ficulty

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #753 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-06 07:26 UTC, kaustubhgupta requested changes
what are links and not found? Both files have no extension

2021-04-06 07:26 UTC, kaustubhgupta commented on LeetCode-Scrapper/format.py
> +f1 = open('hard','r')
What is this file?

2021-04-06 07:26 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +	files['Easy'] = open('easy','a')
Files without extensions?

2021-04-06 07:26 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +	print("done: ",ind)
I have mentioned in the script as well that each question needs to be stored as a single PDF but there is no code for that

2021-04-07 07:31 UTC, kaustubhgupta commented
@AshuKV You need implement this in the same way as it's done here: https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/837

2021-04-08 19:28 UTC, AshuKV reviewed
I have reviewed the changes

2021-04-08 19:34 UTC, AshuKV commented
I have [committed](https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/833/commits/068d694593cc114f16b397b8abc1c47a2f67da69) the new files, please review it and merge it accordingly.

2021-04-09 13:43 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +driver = webdriver.Chrome("C:/Softwares/chromedriver_win32/chromedriver")
Take input for chrome driver path

2021-04-10 12:06 UTC, AshuKV reviewed
I have reviewed the files. You can merge the PR now.

2021-04-11 04:36 UTC, kaustubhgupta requested changes

2021-04-11 04:36 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +
Where is the input for chrome driver path?

2021-04-13 04:51 UTC, kaustubhgupta commented
@AshuKV?

2021-04-13 04:53 UTC, AshuKV commented
Hey @kaustubhgupta I would be pushing the code by EOD today

2021-04-13 19:14 UTC, AshuKV reviewed
Pls confirm that adding path in this manner works.

2021-04-14 03:23 UTC, kaustubhgupta reviewed
Your code is way to similar to one merged earlier for CodeChef scrapping: https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Codechef%20Scrapper/codechef.py

@santushtisharma10 @antrikshmisri

2021-04-14 03:23 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +chromeDriverPath=  "C:\chromedriver_win32\chromedriver.exe";
When I say take input for chrome driver path, I mean to say let the user enter the path of their chrome driver via the terminal. use input function

2021-04-14 05:06 UTC, santushtisharma10 commented
Yes @kaustubhgupta , even the comments and function names are exactly same.

2021-04-15 02:50 UTC, kaustubhgupta commented
PR closed and issue unassigned

2021-04-15 02:50 UTC, closed without merging