Bag of words model
avinashkranjan/Amazing-Python-Scripts pull request #836
Opened 2021-04-05 19:32 UTC by zaverisanya

# Description

Domain- NLP
The objective of this script is to 1) tokenize the sentences taken from user. 2) transforming text to vectors where each word and its count is a feature. 3) Create dataframe where dataframe is an analogy to excel-spreadsheet . The data will be also stored in excel sheet.

## Fixes #822 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-05 19:40 UTC, zaverisanya commented
@kaustubhgupta  @santushtisharma10 please check!

2021-04-06 07:31 UTC, kaustubhgupta reviewed
You have used all the already available libraries and methods, not from scratch. This needs a level decrement. Level3 is not appropriate for this. If you cannot implement this then we can still merge this as level1 only. 

@santushtisharma10, @antrikshmisri thoughts?

2021-04-06 07:42 UTC, zaverisanya commented
I agree that I have used the libraries but I don't think that the level should be decremented because it requires logic to build the script and we need to know how to use the libraries to build the script.  I have spent more than a day to work on this issue which is the ideal time frame for the issue of level 3.  Also the output and script type should be the decisive factor for level, not based on the libraries used. This is my justification to keep it as level 3. Otherwise, the decision is upto you. @kaustubhgupta @santushtisharma10 @antrikshmisri

2021-04-07 06:56 UTC, kaustubhgupta commented
> I agree that I have used the libraries but I don't think that the level should be decremented because it requires logic to build the script and we need to know how to use the libraries to build the script. I have spent more than a day to work on this issue which is the ideal time frame for the issue of level 3. Also the output and script type should be the decisive factor for level, not based on the libraries used. I feel it will be kind of unfair if you decrement the level. This is my justification to keep it as level 3. Otherwise, the decision is upto you. @kaustubhgupta @santushtisharma10 @antrikshmisri

It would be unfair for us to approve this as level3. You can check out other level3 codes merged, also as the level3 weightage has been shifted to 45 points, we need to decrease the level. Level2 would be perfect for this, @antrikshmisri @santushtisharma10?

2021-04-07 07:12 UTC, antrikshmisri commented
> > I agree that I have used the libraries but I don't think that the level should be decremented because it requires logic to build the script and we need to know how to use the libraries to build the script. I have spent more than a day to work on this issue which is the ideal time frame for the issue of level 3. Also the output and script type should be the decisive factor for level, not based on the libraries used. I feel it will be kind of unfair if you decrement the level. This is my justification to keep it as level 3. Otherwise, the decision is upto you. @kaustubhgupta @santushtisharma10 @antrikshmisri
> 
> It would be unfair for us to approve this as level3. You can check out other level3 codes merged, also as the level3 weightage has been shifted to 45 points, we need to decrease the level. Level2 would be perfect for this, @antrikshmisri @santushtisharma10?

@kaustubhgupta Agreed 👍🏻

2021-04-07 07:17 UTC, zaverisanya commented
> > I agree that I have used the libraries but I don't think that the level should be decremented because it requires logic to build the script and we need to know how to use the libraries to build the script. I have spent more than a day to work on this issue which is the ideal time frame for the issue of level 3. Also the output and script type should be the decisive factor for level, not based on the libraries used. I feel it will be kind of unfair if you decrement the level. This is my justification to keep it as level 3. Otherwise, the decision is upto you. @kaustubhgupta @santushtisharma10 @antrikshmisri
> 
> It would be unfair for us to approve this as level3. You can check out other level3 codes merged, also as the level3 weightage has been shifted to 45 points, we need to decrease the level. Level2 would be perfect for this, @antrikshmisri @santushtisharma10?

Okay sir, no issues @kaustubhgupta

2021-04-07 07:35 UTC, kaustubhgupta requested changes
Remove bowp.xlsx and do the following changes too:

2021-04-07 07:35 UTC, kaustubhgupta commented on Bag of words model/README.md
> +[Image](https://i.postimg.cc/pLQq8Vdc/output.png)
```suggestion
![Image](https://i.postimg.cc/pLQq8Vdc/output.png)
```

2021-04-07 07:35 UTC, kaustubhgupta commented on Bag of words model/README.md
> +- This code is written by Sanya Devansh Zaveri. [https://github.com/zaverisanya]
```suggestion
- This code is written by [Sanya Devansh Zaveri](https://github.com/zaverisanya)
```

2021-04-07 07:35 UTC, kaustubhgupta commented on Bag of words model/bow.py
> +cv_dataframe.to_excel('bowp.xlsx', sheet_name='data')
```suggestion
cv_dataframe.to_excel('./Bag of words model/bowp.xlsx', sheet_name='data')
```

2021-04-07 08:34 UTC, zaverisanya commented
> Remove bowp.xlsx and do the following changes too:

2021-04-07 08:37 UTC, zaverisanya commented
> Remove bowp.xlsx and do the following changes too:

Sir how can I remove the committed file  bowp.xlsx, please guide me. I have made the other suggested changes. @kaustubhgupta

2021-04-08 04:52 UTC, kaustubhgupta commented
> > Remove bowp.xlsx and do the following changes too:
> 
> Sir how can I remove the committed file bowp.xlsx, please guide me. I have made the other suggested changes. @kaustubhgupta

You can delete it in your local machine and then make the commit.

2021-04-08 05:28 UTC, zaverisanya commented
Sir, I have made the recommended changes. Please check. @kaustubhgupta

2021-04-08 05:28 UTC, kaustubhgupta approved these changes

2021-04-09 08:30 UTC, antrikshmisri approved these changes

2021-04-09 08:51 UTC, santushtisharma10 approved these changes

2021-04-10 16:45 UTC, avinashkranjan approved these changes
LGTM..💯

2021-04-10 16:45 UTC, merged