Html to md
avinashkranjan/Amazing-Python-Scripts pull request #85
Opened 2020-10-05 19:35 UTC by ragreenburg

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2020-10-05 19:36 UTC, ragreenburg commented
Sorry I made a new pull request because I forgot to make a new branch for the first one. So this one has the README, comments and whatnot.

2020-10-05 19:59 UTC, avinashkranjan requested changes
Add Some SS Showing your Script works

2020-10-05 19:59 UTC, avinashkranjan commented on HTML_to_MD/html_to_md.py
> +    md_save_str = f"You have successfully written the HTML to a MD file and it is saved at {md_path}"
Correct Your Syntax..

![vmware_9X4xSzdeN7](https://user-images.githubusercontent.com/55796944/95125862-2e0a6a00-0773-11eb-9d81-f8f28315dc08.png)

2020-10-13 16:44 UTC, avinashkranjan approved these changes

2020-10-13 16:44 UTC, merged

2020-10-13 16:45 UTC, avinashkranjan commented
@all-contributors please add @ragreenburg for code and documentation