Brick game
avinashkranjan/Amazing-Python-Scripts pull request #854
Opened 2021-04-08 19:37 UTC by Yuvraj-kadale

# Description
Add brick break game

## Fixes #704 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-09 12:51 UTC, kaustubhgupta requested changes
why there are GUI chat application files?

2021-04-09 13:39 UTC, Yuvraj-kadale commented
> why there are GUI chat application files?

Oh, I wasn't aware. No clue btw. I have created a new branch and then sent the PR. I will fix this in a while.

2021-04-10 04:35 UTC, kaustubhgupta requested changes
Bugs in game:
- as soon as application window starts, the game starts without any popup or information. Create a welcome page with two options: Start Game and Exit Game
- When the ball is missed by the slider below, there is no popup or warning that the game is over. Implement that and return to the welcome page in case the user loses the game.
- When the game is over, display the final score of the user  (1 point for each brick touched)

2021-04-10 04:35 UTC, kaustubhgupta commented on Brick Breaker game/Readme.md
> +Run `brick_breaker.py`
```suggestion
Run `python/python3 brick_breaker.py`
```

2021-04-11 04:49 UTC, kaustubhgupta requested changes
- When I click to start the game, the background text should disappear (Click anywhere to start)
- If the user looses the game, display the points scored, and again display "Click anywhere to start)

2021-04-13 04:53 UTC, kaustubhgupta commented
@Yuvraj-kadale updates?

2021-04-13 05:15 UTC, Yuvraj-kadale commented
> @Yuvraj-kadale updates?

I am out of station.  Will send a PR by tommorow EoD . Will that work?

2021-04-13 05:15 UTC, kaustubhgupta commented
> > @Yuvraj-kadale updates?
> 
> I am out of station. Will send a PR by tommorow EoD . Will that work?

sure!

2021-04-15 03:02 UTC, kaustubhgupta approved these changes
Although score thing is still missing, but I will approve it

2021-04-15 06:54 UTC, antrikshmisri approved these changes
LGTM 👍🏻

2021-04-16 05:48 UTC, santushtisharma10 approved these changes

2021-04-19 07:23 UTC, avinashkranjan approved these changes
LGTM..

2021-04-19 07:23 UTC, merged