Added Photo_to_Ascii
avinashkranjan/Amazing-Python-Scripts pull request #855
Opened 2021-04-09 06:16 UTC by Avishake007

# Description

Here I have added photo to ascii feature which will convert your photo to ascii

## Fixes #847 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Previously

![photo_to_ascii](https://user-images.githubusercontent.com/56298861/114136937-19c54680-9929-11eb-9c4c-fbe69f2af104.png)

After

![photo_to_ascii(2)](https://user-images.githubusercontent.com/56298861/114136974-247fdb80-9929-11eb-90b4-66296b9c15d7.PNG)

2021-04-09 13:02 UTC, kaustubhgupta requested changes

2021-04-09 13:02 UTC, kaustubhgupta commented on Photo To Ascii/photo_to_ascii.py
> +    with open("ascii_image.txt", "w") as f:
```suggestion
    with open("./Photo To Ascii/ascii_image.txt", "w") as f:
```

2021-04-09 13:02 UTC, kaustubhgupta commented on Photo To Ascii/photo_to_ascii.py
> +    with open("ascii_image.txt", "w") as f:
Make file name as "{image_name} (ASCII).txt"

2021-04-09 14:54 UTC, Avishake007 commented
@kaustubhgupta  It's done . Kindly check it

2021-04-10 04:36 UTC, kaustubhgupta approved these changes

2021-04-10 05:56 UTC, Kushal997-das approved these changes
👍

2021-04-10 05:58 UTC, santushtisharma10 approved these changes
LGTM

2021-04-10 07:36 UTC, antrikshmisri approved these changes

2021-04-10 16:43 UTC, avinashkranjan approved these changes
LGTM..💯

2021-04-10 16:43 UTC, merged