AWS management Script - issue #856
avinashkranjan/Amazing-Python-Scripts pull request #889
Opened 2021-04-12 07:17 UTC by shantamsultania

2021-04-13 05:31 UTC, kaustubhgupta requested changes
- Create a folder named: "AWS Management Scripts" and put both the folders under it.
- Create a separate readme for this folder with relevant screenshots: AWS Automation Script for AWS endorsement management

2021-04-13 05:33 UTC, kaustubhgupta commented
Also, fix these errors:

![image](https://user-images.githubusercontent.com/43691873/114501573-e136ad00-9c47-11eb-96d9-91fc1a36c09e.png)

2021-04-13 07:27 UTC, Sanskrutim17 approved these changes

2021-04-13 13:26 UTC, shantamsultania commented
> Also, fix these errors:
> 
> ![image](https://user-images.githubusercontent.com/43691873/114501573-e136ad00-9c47-11eb-96d9-91fc1a36c09e.png)

hey @kaustubhgupta these changes are just call variables as currently this script is not being used by anyone this error is being displayed that is of unused variables I don't think there is a change required for the same

2021-04-13 13:26 UTC, shantamsultania commented
> * Create a folder named: "AWS Management Scripts" and put both the folders under it.
> * Create a separate readme for this folder with relevant screenshots: AWS Automation Script for AWS endorsement management

ok will do the same

2021-04-14 03:46 UTC, kaustubhgupta commented
> > Also, fix these errors:
> > ![image](https://user-images.githubusercontent.com/43691873/114501573-e136ad00-9c47-11eb-96d9-91fc1a36c09e.png)
> 
> hey @kaustubhgupta these changes are just call variables as currently this script is not being used by anyone this error is being displayed that is of unused variables I don't think there is a change required for the same

Okay got it, that's the problem with the linter, it can't handle dynamic modules.

2021-04-14 17:29 UTC, shantamsultania commented
hey @kaustubhgupta I have made the requested changes please look into it as for screenshots/images in AWS Automation Script for AWS endorsement that will be not required as I think they are management scripts not a particular scripts related to a endorsement and this can change from user/ client point of view

2021-04-15 03:29 UTC, kaustubhgupta requested changes

2021-04-15 03:29 UTC, kaustubhgupta commented on AWS Management Scripts/AWS Automation Script for AWS endorsement management/Readme.md
> +this provides features like :
```suggestion
This provides features like :
```

2021-04-15 03:29 UTC, kaustubhgupta commented on AWS Management Scripts/AWS Automation Script for AWS endorsement management/Readme.md
> +EC2 :
```suggestion
### EC2 :
```

2021-04-15 03:29 UTC, kaustubhgupta commented on AWS Management Scripts/AWS Automation Script for AWS endorsement management/Readme.md
> +RDS :
```suggestion
### RDS : 
```

2021-04-15 06:32 UTC, antrikshmisri commented
@kaustubhgupta I don't have much knowledge about AWS so, can't comment on this.

2021-04-15 14:53 UTC, shantamsultania commented
hey @kaustubhgupta I think all the minor changes requested must be cleared out and we can merge it up if the PA or the mentors don't have any issues with it

2021-04-16 07:33 UTC, santushtisharma10 commented
@shantamsultania is it a flask app?

2021-04-16 07:42 UTC, santushtisharma10 requested changes
@shantamsultania remove this empty [file](https://github.com/shantamsultania/Amazing-Python-Scripts/blob/master/AWS%20Management%20Scripts/AWS%20testing%20Script/__init__.py)

2021-04-16 07:45 UTC, shantamsultania commented
hey @santushtisharma10 there are 2 scripts in this 1 AWS testing script is a Flask app but not 2. that is AWS script for endorsement

2021-04-17 04:11 UTC, kaustubhgupta approved these changes

2021-04-17 07:10 UTC, santushtisharma10 approved these changes

2021-04-17 10:22 UTC, shantamsultania commented
hey @kaustubhgupta as all the reviews are approved can we can merge this so that I can start working on the next issue.

2021-04-17 11:07 UTC, kaustubhgupta commented
> hey @kaustubhgupta as all the reviews are approved can we can merge this so that I can start working on the next issue.

A review from one mentor is still missing. You can work on other issues by making different branches for each issue but as you have made the PR using the master branch, you will need to wait for this PR to be merged.

2021-04-17 11:43 UTC, shantamsultania commented
> > hey @kaustubhgupta as all the reviews are approved can we can merge this so that I can start working on the next issue.
> 
> A review from one mentor is still missing. You can work on other issues by making different branches for each issue but as you have made the PR using the master branch, you will need to wait for this PR to be merged.

I think you are waiting for a comment by @antrikshmisri he has already commented above that he is not that much aware of AWS thus he cannot comment on the same I think we can move this up for PA review and if he is ok we can close this up

2021-04-17 11:45 UTC, kaustubhgupta commented
> > > hey @kaustubhgupta as all the reviews are approved can we can merge this so that I can start working on the next issue.
> > 
> > 
> > A review from one mentor is still missing. You can work on other issues by making different branches for each issue but as you have made the PR using the master branch, you will need to wait for this PR to be merged.
> 
> I think you are waiting for a comment by @antrikshmisri he has already commented above that he is not that much aware of AWS thus he cannot comment on the same I think we can move this up for PA review and if he is ok we can close this up

We have another mentor @Kushal997-das

2021-04-17 11:58 UTC, antrikshmisri approved these changes

2021-04-17 15:01 UTC, shantamsultania commented
> > > > hey @kaustubhgupta as all the reviews are approved can we can merge this so that I can start working on the next issue.
> > > 
> > > 
> > > A review from one mentor is still missing. You can work on other issues by making different branches for each issue but as you have made the PR using the master branch, you will need to wait for this PR to be merged.
> > 
> > 
> > I think you are waiting for a comment by @antrikshmisri he has already commented above that he is not that much aware of AWS thus he cannot comment on the same I think we can move this up for PA review and if he is ok we can close this up
> 
> We have another mentor @Kushal997-das

ok waiting for his review on the same

2021-04-19 07:23 UTC, avinashkranjan approved these changes
LGTM..Great Work @shantamsultania

2021-04-19 07:23 UTC, merged