Pacman Game
avinashkranjan/Amazing-Python-Scripts pull request #890
Opened 2021-04-12 16:26 UTC by sayantani11

# Description

This is a simple pacman game, just like original.
There are 4 enemies and one pacman, the task is to get as many coins as possible within 3 chances.

## Fixes #809 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings

2021-04-13 05:50 UTC, kaustubhgupta reviewed
These are your errors returned by bot:

2021-04-13 05:50 UTC, kaustubhgupta commented on Pacman-Game/Pacman.py
> +        self.background = pygame.image.load('maze.png')
```suggestion
        self.background = pygame.image.load('./Pacman-Game/maze.png')
```

2021-04-13 05:50 UTC, kaustubhgupta commented on Pacman-Game/Pacman.py
> +        with open("walls.txt",'r') as file:
```suggestion
        with open("./Pacman-Game/walls.txt",'r') as file:
```

2021-04-13 10:26 UTC, sayantani11 commented
okay I will check the errors today itself

2021-04-14 14:29 UTC, sayantani11 commented
@kaustubhgupta I tried fixing the errors what are the errors now.....The problem is I can only run the code in jupyter lab and sometimes it avoids catching the errors

2021-04-15 03:32 UTC, kaustubhgupta commented
> @kaustubhgupta I tried fixing the errors what are the errors now.....The problem is I can only run the code in jupyter lab and sometimes it avoids catching the errors

Hmm, you don't have any IDE setup like VSCODE or Pycharm (Python-specific)? If not then you should at least setup vscode as it will be beneficial for your future projects as well!

2021-04-15 03:50 UTC, kaustubhgupta requested changes
The game is not starting. It terminates as soon as the pygame messge in the terminal comes:
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
```

2021-04-15 15:19 UTC, sayantani11 commented
> > @kaustubhgupta I tried fixing the errors what are the errors now.....The problem is I can only run the code in jupyter lab and sometimes it avoids catching the errors
> 
> Hmm, you don't have any IDE setup like VSCODE or Pycharm (Python-specific)? If not then you should at least setup vscode as it will be beneficial for your future projects as well!

I have both PyCharm and VScode but the problem is I guess the path where I downloaded a few of the python packages, and the path of VScode or Pycharm isn't same

2021-04-15 15:22 UTC, sayantani11 commented
I am looking for the issue.... I will try fixing it

2021-04-17 04:12 UTC, kaustubhgupta commented
@sayantani11 updates?

2021-04-17 05:12 UTC, sayantani11 commented
@kaustubhgupta I am working on it ......Give me today's time.... If I am unable then I will inform

2021-04-18 06:13 UTC, sayantani11 commented
@kaustubhgupta I guess this won't fix

2021-04-19 02:33 UTC, kaustubhgupta commented
@sayantani11 oh okay no issue, you can work on other issues now

2021-04-19 02:33 UTC, closed without merging