Fast algorithm
avinashkranjan/Amazing-Python-Scripts pull request #891
Opened 2021-04-12 19:18 UTC by ShubhamGupta577

# Description

Added the script for implementation of Fast Algorithm of OpenCV.

## Fixes #887 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)
## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-12 19:21 UTC, ShubhamGupta577 commented
@kaustubhgupta Please review this PR.

2021-04-13 05:57 UTC, kaustubhgupta requested changes
Rename folder to Fast Algorithm (Corner Detection). Other changes:

2021-04-13 05:57 UTC, kaustubhgupta commented on Fast Algorithm/Fast_Algorithm.py
> +path=input("Enter the path of uploaded image: ")
```suggestion
path=input("Enter the path of image: ")
```

2021-04-13 05:57 UTC, kaustubhgupta commented on Fast Algorithm/Fast_Algorithm.py
> +cv.imshow('Final',final)
Save the final image. Name it as: "image_name (detected).jpg" . Also, make sure to save it in the same folder where the script lies. For doing this, add this to the saving image path: `./folder-name/image_name (detected).jpg`

2021-04-13 12:44 UTC, ShubhamGupta577 commented
@kaustubhgupta, Requested changes are done. Please review this.

2021-04-14 02:15 UTC, Kushal997-das approved these changes
LGTM 💯

2021-04-14 03:50 UTC, kaustubhgupta requested changes

2021-04-14 03:50 UTC, kaustubhgupta commented on Fast Algorithm (Corner Detection)/Fast_Algorithm.py
> +cv.imwrite('./folder-name/image_name (detected).jpg',final)
by image name, I mean to say if I passed an image named "abc.jpg", then the output image should be "abc (detected) .jpg" 

Fix this. (Hint: Use f-strings)

2021-04-15 03:54 UTC, kaustubhgupta approved these changes

2021-04-15 06:44 UTC, antrikshmisri approved these changes

2021-04-16 06:12 UTC, santushtisharma10 approved these changes
LGTM

2021-04-19 07:22 UTC, avinashkranjan approved these changes
LGTM..🚩

2021-04-19 07:24 UTC, merged