Udemy scraper
avinashkranjan/Amazing-Python-Scripts pull request #899
Opened 2021-04-13 20:05 UTC by Ayushjain2205

# Description

Script added to scrape udemy course information and store it in a database

## Fixes #862 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-15 04:58 UTC, kaustubhgupta requested changes

2021-04-15 04:58 UTC, kaustubhgupta commented on Udemy Scraper/fetcher.py
> +driver_path = input("Enter chrome driver path")
```suggestion
driver_path = input("Enter chrome driver path: ")
```

2021-04-15 04:58 UTC, kaustubhgupta commented on Udemy Scraper/fetcher.py
> +category = input("Enter course category:")
Can you display some of the categories that are available on Udemy? A user like me is not aware of different options in category. Display them as a list to the user. Also this minor change:

```suggestion
category = input("Enter course category: ")
```

2021-04-15 04:58 UTC, kaustubhgupta commented on Udemy Scraper/fetcher.py
> +        con = sqlite3.connect('udemyDatabase.db')
```suggestion
        con = sqlite3.connect('./Udemy Scraper/udemyDatabase.db')
```

2021-04-15 04:58 UTC, kaustubhgupta commented on Udemy Scraper/display.py
> +        con = sqlite3.connect('udemyDatabase.db')
```suggestion
        con = sqlite3.connect('./Udemy Scraper/udemyDatabase.db')
```

2021-04-15 11:17 UTC, Ayushjain2205 commented
@kaustubhgupta  I have made the suggested changes

2021-04-16 04:17 UTC, kaustubhgupta approved these changes
💯 Good improvement from first PR

2021-04-16 05:55 UTC, santushtisharma10 approved these changes
@Ayushjain2205 💯

2021-04-16 16:24 UTC, Kushal997-das approved these changes
LGTM 👍

2021-04-17 12:28 UTC, santushtisharma10 commented
@antrikshmisri

2021-04-17 12:34 UTC, antrikshmisri approved these changes

2021-04-19 07:18 UTC, avinashkranjan approved these changes
LGTM..🚩

2021-04-19 07:18 UTC, merged