Twitter Scraper using snscrape
avinashkranjan/Amazing-Python-Scripts pull request #903
Opened 2021-04-14 16:20 UTC by RohiniRG

# Description

Using Python's snscrape, we scrape tweets associated with a particular hashtag. Snscrape is a python library that scrapes twitter without the intervention of tweepy.

## Fixes #869 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-15 05:06 UTC, kaustubhgupta requested changes
Perfect, just a minor suggestion:

2021-04-15 05:06 UTC, kaustubhgupta commented on Twitter_Scraper_without_API/display_hashtags.py
> +    path = os.path.abspath('TwitterDatabase.db')
```suggestion
    path = os.path.abspath('./Twitter_Scraper_without_API/TwitterDatabase.db')
```

2021-04-15 05:06 UTC, kaustubhgupta commented on Twitter_Scraper_without_API/fetch_hashtags.py
> +    con = sqlite3.connect('TwitterDatabase.db')
```suggestion
    con = sqlite3.connect('./Twitter_Scraper_without_API/TwitterDatabase.db')
```

2021-04-15 05:43 UTC, RohiniRG commented
@kaustubhgupta made the requested changes, have a look

2021-04-16 04:18 UTC, kaustubhgupta approved these changes
💯

2021-04-16 16:23 UTC, Kushal997-das approved these changes
LGTM 👍

2021-04-17 12:39 UTC, santushtisharma10 approved these changes
Nice @RohiniRG 💯

2021-04-19 19:59 UTC, antrikshmisri approved these changes

2021-04-23 07:25 UTC, avinashkranjan approved these changes

2021-04-23 07:27 UTC, merged