Added Todolist Cli-Version
avinashkranjan/Amazing-Python-Scripts pull request #907
Opened 2021-04-15 14:13 UTC by Avishake007

# Description
Here I have created todolist in cli version
## Fixes #871

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-16 04:20 UTC, kaustubhgupta requested changes

2021-04-16 04:20 UTC, kaustubhgupta commented on TODO (CLI-VER)/todolist.py
> +    f=open("todolist.txt")
```suggestion
    f=open("./TODO (CLI-VER)/todolist.txt")
```

2021-04-16 04:20 UTC, kaustubhgupta commented on TODO (CLI-VER)/todolist.py
> +
Remove one blank line

2021-04-17 04:32 UTC, kaustubhgupta requested changes
Code works perfectly, just this left:

2021-04-17 04:32 UTC, kaustubhgupta commented on TODO (CLI-VER)/todolist.py
> +    f=open("todolist.txt")
This is left

2021-04-17 06:26 UTC, kaustubhgupta approved these changes
💯

2021-04-17 18:37 UTC, Kushal997-das approved these changes
LGTM 👍

2021-04-18 06:49 UTC, santushtisharma10 approved these changes

2021-04-19 19:59 UTC, antrikshmisri approved these changes

2021-04-23 07:25 UTC, avinashkranjan approved these changes

2021-04-23 07:27 UTC, merged