#913 Codeforces_Problem_Scraper Added
avinashkranjan/Amazing-Python-Scripts pull request #919
Opened 2021-04-16 18:19 UTC by iamakkkhil

# Description

This python script will let you download Problem Statements from Codeforces and save them as a pdf file. The script uses Selenium Webdriver and fpdf library. Selenium is used with Chrome Webdriver.

## Fixes #913 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-17 07:08 UTC, santushtisharma10 requested changes

2021-04-17 07:08 UTC, santushtisharma10 commented on Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +    driver = webdriver.Chrome(r"chromedriver_win32\chromedriver.exe", options=options)
@iamakkkhil take the input of chrome driver path from user

2021-04-17 18:26 UTC, santushtisharma10 requested changes

2021-04-17 18:26 UTC, santushtisharma10 commented on Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +
```suggestion

DRIVER_PATH = input("Enter the chrome driver path : ")


```

2021-04-17 18:26 UTC, santushtisharma10 commented on Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +
Rest is working fine

2021-04-19 03:11 UTC, kaustubhgupta requested changes
This is scrapping a single problem. I told you to implement it in the same way as https://github.com/avinashkranjan/Amazing-Python-Scripts/tree/master/Codechef%20Scrapper while assigning the issue. You need to implement like this:

Come up with a script that scraps `n` number of problems from any `category/difficulty` provided by the user and stores all the `n` problems separately in PDFs. The PDF file should contain the problem title, statement, and test cases.

User Input: `n` and `category/difficulty` of the problem
Expected Output: `n` PDF files

2021-04-22 05:25 UTC, kaustubhgupta requested changes
Just minor changes, your code works:

2021-04-22 05:25 UTC, kaustubhgupta commented on Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +DRIVER_PATH = ''
remove this line as you have shifted this in main function

2021-04-22 05:25 UTC, kaustubhgupta commented on Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +    print("\nEnter the Range between 800 to 3500: ")
```suggestion
    print("\nEnter the Range of difficulty between 800 to 3500: ")

```

2021-04-22 05:25 UTC, kaustubhgupta commented on Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
> +    target_folder = './problems_pdf'
```suggestion
    target_folder = './Coderforces_Problem_Scrapper/problems_pdf'

```

2021-04-22 07:52 UTC, kaustubhgupta approved these changes

2021-04-23 06:43 UTC, santushtisharma10 approved these changes

2021-04-23 07:55 UTC, antrikshmisri approved these changes

2021-04-24 06:41 UTC, avinashkranjan approved these changes

2021-04-24 06:41 UTC, merged