Piglatin_translator scripts
avinashkranjan/Amazing-Python-Scripts pull request #921
Opened 2021-04-17 03:11 UTC by archanagandhi

# Description
Scripts and README file has been added as per guidelines
## Fixes #916 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-17 06:54 UTC, santushtisharma10 requested changes
@archanagandhi translation of `my` should be `ymay` but your code gives `myay`

2021-04-17 16:44 UTC, santushtisharma10 commented
![image](https://user-images.githubusercontent.com/60578091/115120226-ff930480-9fc9-11eb-9832-87dc98c9a839.png)

@archanagandhi  fix it

2021-04-18 05:18 UTC, archanagandhi commented
Hey @santushtisharma10, there is no pig latin for single letter consonants. The only single letter word in english are 'A' and 'I' only. You have used 'S' between the sentence so it shows error.

2021-04-18 06:44 UTC, santushtisharma10 approved these changes

2021-04-18 17:39 UTC, Kushal997-das approved these changes
LGTM 💯

2021-04-19 03:16 UTC, kaustubhgupta requested changes

2021-04-19 03:16 UTC, kaustubhgupta commented on Piglatin_Translator/README.md
> +# Rules
```suggestion
## Rules
```

2021-04-19 03:16 UTC, kaustubhgupta commented on Piglatin_Translator/README.md
> +# Input
```suggestion
## How to run?
```

2021-04-19 03:16 UTC, kaustubhgupta commented on Piglatin_Translator/README.md
> + - Run the script ```piglatin.py```
```suggestion
 - Run the script ```python piglatin.py```
```

2021-04-19 03:16 UTC, kaustubhgupta commented on Piglatin_Translator/README.md
> + # Output
```suggestion
## Output
```

2021-04-19 03:16 UTC, kaustubhgupta commented on Piglatin_Translator/README.md
> +## [Author](https://github.com/archanagandhi)
```suggestion
## Author
```

2021-04-19 03:16 UTC, kaustubhgupta commented on Piglatin_Translator/README.md
> +Archana Gandhi
```suggestion
[Archana Gandhi](https://github.com/archanagandhi)
```

2021-04-19 19:58 UTC, antrikshmisri approved these changes

2021-04-20 03:07 UTC, kaustubhgupta approved these changes

2021-04-23 07:25 UTC, avinashkranjan approved these changes

2021-04-23 07:26 UTC, merged