Malaria Detection
avinashkranjan/Amazing-Python-Scripts pull request #927
Opened 2021-04-18 16:07 UTC by ayush-raj8

# Description
Python script and model to detect malaria infected cells.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings

2021-04-19 04:27 UTC, kaustubhgupta requested changes

2021-04-19 04:27 UTC, kaustubhgupta commented on Malaria/Dataset/Dataset Link.txt
> +
this file is not needed , you can delete it

2021-04-19 04:27 UTC, kaustubhgupta commented on Malaria/main.py
> +img = Image.open("Images/cell1.jpg")
Take input for image path from user

2021-04-19 04:27 UTC, kaustubhgupta commented on Malaria/main.py
> +model_path = "Models/malaria.h5"
```suggestion
model_path = "./Malaria/Models/malaria.h5"
```

2021-04-19 04:27 UTC, kaustubhgupta commented on Malaria/Model development/malariadetection.ipynb
> +{
Convert this notebook into .py script and delete this notebook

2021-04-20 06:02 UTC, kaustubhgupta requested changes
Delete the malaraidetection.ipynb file along with this change:

2021-04-20 06:02 UTC, kaustubhgupta commented on Malaria/script.py
> +# importing the libraries for loading data and visualisation
name this file as `model_training.py` instead of `script.py`

2021-04-21 04:22 UTC, kaustubhgupta requested changes
For the third time: DELETE THIS FILE! malariadetection.ipynb

2021-04-21 04:22 UTC, kaustubhgupta commented on Malaria/main.py
> +val_path = input("Enter image path name eg. Images/cell1.jpg")
```suggestion
val_path = input("Enter image path name eg. Images/cell1.jpg: ")
```

2021-04-21 06:23 UTC, ayush-raj8 commented
@kaustubhgupta  This new deep source python is showing errors because of comments and line too long.  This code runs perfectly fine on any python ide e.g. Pycharm.
Line too long cannot be removed as it involves model formation.
![image](https://user-images.githubusercontent.com/52033949/115506022-ffc82400-a297-11eb-9e0b-f405163a81d1.png)
![image](https://user-images.githubusercontent.com/52033949/115506065-0d7da980-a298-11eb-8006-b1abe2154c72.png)

Lines will have more than 88 characters , because this is the standard way of training , testing and forming CNN.

2021-04-22 05:27 UTC, kaustubhgupta approved these changes

2021-04-22 05:31 UTC, Kushal997-das approved these changes
LGTM 👍

2021-04-23 06:48 UTC, santushtisharma10 approved these changes

2021-04-23 08:00 UTC, antrikshmisri commented
> @kaustubhgupta  This new deep source python is showing errors because of comments and line too long.  This code runs perfectly fine on any python ide e.g. Pycharm.
> Line too long cannot be removed as it involves model formation.
> ![image](https://user-images.githubusercontent.com/52033949/115506022-ffc82400-a297-11eb-9e0b-f405163a81d1.png)
> ![image](https://user-images.githubusercontent.com/52033949/115506065-0d7da980-a298-11eb-8006-b1abe2154c72.png)
> 
> Lines will have more than 88 characters , because this is the standard way of training , testing and forming CNN.
> 

@ayush-raj8 Have a look at pep8 guidelines for long lines [here](https://www.python.org/dev/peps/pep-0008/#:~:text=The%20preferred%20way%20of%20wrapping,a%20backslash%20for%20line%20continuation)

2021-04-26 05:24 UTC, antrikshmisri approved these changes

2021-04-26 09:12 UTC, avinashkranjan approved these changes
LGTM

2021-04-26 09:13 UTC, merged