Leetcode Scrapper
avinashkranjan/Amazing-Python-Scripts pull request #939
Opened 2021-04-19 18:58 UTC by AshuKV

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #753 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

2021-04-20 06:45 UTC, kaustubhgupta requested changes

2021-04-20 06:45 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +print("Enter Chrome Driver path")
```suggestion
print("Enter Chrome Driver path: ")
```

2021-04-20 06:45 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +inp = input()
use better variable name

2021-04-20 06:45 UTC, kaustubhgupta commented on LeetCode-Scrapper/README.md
> +To run this script, you need to have selenium installed and configure webdriver to use chrome browser in your$PATH. You can directly download chrome driver from the link below- https://chromedriver.c
Do you think this chrome driver explanation is still needed when you have taken input for the chrome driver path?

2021-04-20 06:45 UTC, kaustubhgupta commented on LeetCode-Scrapper/README.md
> +` driver = webdriver.Chrome('/path/to/chromedriver') `
not needed

2021-04-20 06:45 UTC, kaustubhgupta commented on LeetCode-Scrapper/ques.py
> +    pdf.output(title+".pdf")
```suggestion
    pdf.output("./LeetCode-Scrapper/"+ title+".pdf")   
```

2021-04-22 05:29 UTC, kaustubhgupta commented
@AshuKV updates on this?

2021-04-23 03:40 UTC, kaustubhgupta commented
@AshuKV will you update the PR today? that's the max extension I can give now, else the PR will be closed. Then don't message us that you were not informed.

2021-04-23 18:33 UTC, AshuKV reviewed
I have resolved the changes. You could merge the PR now.

2021-04-24 03:59 UTC, kaustubhgupta approved these changes

2021-04-25 15:43 UTC, antrikshmisri approved these changes

2021-04-25 18:42 UTC, santushtisharma10 approved these changes

2021-04-26 09:12 UTC, avinashkranjan approved these changes
LGTM

2021-04-26 09:13 UTC, merged