Instagram follow  not follow
avinashkranjan/Amazing-Python-Scripts pull request #948
Opened 2021-04-21 13:19 UTC by nidhivanjare

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #894 

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Added ream me file

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] My documentation follows [`Template for README.md`](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/Template%20for%20README.md)
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Output of my code:

(List of people how do not follow back :)

<img width="883" alt="Screenshot 2021-04-21 at 6 22 12 PM" src="https://user-images.githubusercontent.com/55665104/115560249-070c2380-a2d2-11eb-8349-3436657bc946.png">

2021-04-22 05:48 UTC, nidhivanjare commented
Hey, Can you please merge this PR ??

2021-04-22 06:00 UTC, kaustubhgupta requested changes

2021-04-22 06:00 UTC, kaustubhgupta commented on Instagram Follow- NotFollow/main.py
> +from selenium import webdriver
Print the list of followers and non-followers in a more attractive way. Maybe an ascii table with two columns: followers | non followers

2021-04-22 09:58 UTC, nidhivanjare commented
working on it !!

2021-04-24 04:05 UTC, kaustubhgupta requested changes

2021-04-24 04:05 UTC, kaustubhgupta commented on .vscode/settings.json
> +{
This is still left

2021-04-24 04:05 UTC, kaustubhgupta commented on Instagram Follow- NotFollow/README.md
> +Install Selenium
```suggestion
## Install Selenium
```

2021-04-24 09:54 UTC, nidhivanjare commented
Done ??

2021-04-24 13:42 UTC, kaustubhgupta approved these changes

2021-04-24 14:29 UTC, Kushal997-das approved these changes
LGTM 👍

2021-04-25 14:45 UTC, nidhivanjare commented
Can you merge this PR?

2021-04-25 15:41 UTC, antrikshmisri approved these changes

2021-04-25 15:42 UTC, antrikshmisri commented
> Can you merge this PR?

Only PA can merge the PR

2021-04-26 05:42 UTC, santushtisharma10 approved these changes

2021-04-26 09:12 UTC, avinashkranjan approved these changes
LGTM

2021-04-26 09:13 UTC, merged